(function(){'use strict';
const DEFAULT={profile:{displayName:'SSS',level:78,vip:6},coins:45000,gems:4500,energy:125,maxEnergy:200,hp:6850,maxHp:6850,xp:81431,xpNext:119500,dice:10,stage:7,equipment:0,activeFollower:null,auto:false};
window.TerritoryStore=window.TerritoryStore||{};
const Store=window.TerritoryStore;
Store.state=Object.assign({},DEFAULT);
try{const saved=JSON.parse(localStorage.getItem('territory_store_v1')||'null');if(saved) Store.state=Object.assign({},DEFAULT,saved,{profile:Object.assign({},DEFAULT.profile,saved.profile||{})});}catch(e){}
Store.saveNow=function(){try{localStorage.setItem('territory_store_v1',JSON.stringify(Store.state));}catch(e){}};
Store.getDerivedStats=function(){return {maxHp:Store.state.maxHp,strength:125,defense:98};};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));const target=document.getElementById(id);if(target)target.classList.add('active');if(id==='roadmap')roadmap();if(id==='inventory')inventory();if(id==='shop')shop();if(id==='games')games();}
function home(){show('home')}
function modal(title,body){$('#modalBody').innerHTML='<h2>'+title+'</h2>'+body;$('#modal').classList.add('show')}
$('#modalClose').onclick=()=>$('#modal').classList.remove('show');
function setHomeZones(){const z=$('#homeZones');const add=(cls,x,y,w,h,fn)=>{const b=document.createElement('button');b.className='zone '+cls;b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%;`;b.onclick=fn;z.appendChild(b)};
add('events',1,12,13,10,()=>modal('События','<p>События откроются в следующем обновлении.</p>'));add('daily',1,23,13,10,()=>modal('Ежедневные награды','<p>Награда дня готова.</p><button class="gold" id="claim">ЗАБРАТЬ</button>'));add('quests',1,34,13,10,()=>show('quests'));add('friends',1,45,13,10,()=>modal('Пригласить друзей','<p>Приглашение друга скопировано.</p>'));add('sea',1,56,13,10,()=>modal('Морской набор','<p>Морской набор доступен в Лавке.</p>'));add('shop',88,12,11,10,()=>show('shop'));add('forge',88,23,11,10,()=>modal('Кузница','<p>Кузница готовит улучшения экипировки.</p>'));add('tests',88,34,11,10,()=>modal('Испытания','<p>Испытания доступны в текущей главе.</p>'));add('streets',88,45,11,10,()=>modal('Захват улиц','<p>Система улиц готовится.</p>'));add('arena',86,55,13,15,()=>show('arena'));add('roadmap',27,12,47,11,()=>show('roadmap'));add('inventory',14,88,14,11,()=>show('inventory'));add('hero',28,88,14,11,()=>show('hero'));add('battle',42,87,16,12,()=>show('arena'));add('questsBottom',57,88,14,11,()=>show('quests'));add('games',70,88,14,11,()=>show('games'));add('clan',84,88,16,11,()=>show('clan'));}
function arenaZones(){const z=$('#arenaZones');const add=(cls,x,y,w,h,fn)=>{const b=document.createElement('button');b.className='zone '+cls;b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%;`;b.onclick=fn;z.appendChild(b)};
// 4 attack / 4 defense hit zones
[['attack',0,15,11,10,'Голова'],['attack',0,27,11,10,'Грудь'],['attack',0,39,11,10,'Пояс'],['attack',0,51,11,10,'Ноги'],['def',89,15,11,10,'Голова'],['def',89,27,11,10,'Грудь'],['def',89,39,11,10,'Пояс'],['def',89,51,11,10,'Ноги']].forEach(a=>add(a[0],a[1],a[2],a[3],a[4],()=>modal('Тактика','<p>Выбрана зона: <b>'+a[5]+'</b>.</p>')));
add('tactics',1,66,25,7,()=>modal('Тактика','<p>Выберите атаку и две зоны защиты.</p>'));add('auto',27,66,22,7,()=>{Store.state.auto=!Store.state.auto;Store.saveNow();modal('Авто-бой','<p>Авто-бой: <b>'+(Store.state.auto?'ВКЛ':'ВЫКЛ')+'</b></p>')});add('hit',49,66,25,7,()=>modal('Удар','<p>SSS наносит удар. Урон: <b>24</b>.</p>'));add('timer',76,66,23,7,()=>modal('Таймер','<p>Следующий ход через 15 секунд.</p>'));
for(let i=0;i<7;i++)add('equip',1+i*12,73,11,7,()=>{Store.state.equipment=i;Store.saveNow();modal('Снаряжение','<p>Выбран слот '+(i+1)+' / 7.</p>')});for(let i=0;i<7;i++)add('cons',1+i*12,80,11,6,()=>modal('Предмет','<p>Предмет использован.</p>'));
add('chat',1,86,98,8,()=>modal('Чат боя','<p>SSS: Удачи!</p><p>Ragnar: В бой!</p><input class="chatInput" placeholder="Сообщение"><button class="gold" id="send">ОТПРАВИТЬ</button>'));add('home',0,92,14,8,home);add('inventory',14,92,14,8,()=>show('inventory'));add('hero',28,92,14,8,()=>show('hero'));add('battle',42,92,14,8,()=>show('arena'));add('quests',56,92,14,8,()=>show('quests'));add('games',70,92,14,8,()=>show('games'));add('clan',84,92,16,8,()=>show('clan'));}
function roadmap(){const n=$('#roadNodes');n.innerHTML='';for(let i=1;i<=7;i++){const b=document.createElement('button');b.className='node '+(i<Store.state.stage?'done ':'')+(i===Store.state.stage?'current':'');b.textContent=i;b.onclick=()=>{Store.state.stage=i;Store.saveNow();roadmap()};n.appendChild(b)}$('#stageTitle').textContent='2-'+Store.state.stage;}
const inv=[['⚔️','Топор','Lv.102'],['🪖','Шлем','Lv.98'],['🛡️','Доспех','Lv.100'],['🎗️','Пояс','Lv.95'],['🥾','Сапоги','Lv.95'],['💍','Кольцо','Lv.97'],['🔮','Амулет','Lv.101'],['🧪','Эликсир HP','5/5']];
function cards(id,arr){$(id).innerHTML=arr.map((x,i)=>`<button class="card" data-item="${i}"><div>${x[0]}</div><b>${x[1]}</b><span>${x[2]}</span></button>`).join('');$$('#'+id+' .card').forEach(b=>b.onclick=()=>modal('Предмет',`<p>${arr[Number(b.dataset.item)][1]}</p><button class="gold">ЭКИПИРОВАТЬ</button>`))}
function inventory(){cards('inventoryGrid',inv)}
function shop(){cards('shopGrid',[['🧪','Зелье HP','5/5'],['🔵','Энергия','3/3'],['🔴','Атака','1/5'],['🟡','Защита','2/5'],['🟣','Адреналин','1/5'],['💠','Ускорение','1/5']])}
function games(){const b=$('#board');b.innerHTML='';for(let i=0;i<25;i++){const c=document.createElement('button');c.className='cell '+(i===Store.state.pos?'active':'');c.textContent=i+1;c.onclick=()=>{Store.state.pos=i;Store.saveNow();games()};b.appendChild(c)}$$('[data-dice]').forEach(x=>x.textContent=Store.state.dice)}
$('#roll').onclick=()=>{if(!Store.state.dice){modal('Кубики','<p>Кубики закончились.</p>');return}Store.state.dice--;Store.state.pos=(Store.state.pos||0)+1+Math.floor(Math.random()*6);Store.state.pos%=25;Store.saveNow();games();$('#rollLog').textContent='Бросок выполнен. Позиция '+(Store.state.pos+1)};
$('#followersBtn').onclick=()=>modal('Последователи','<div class="followers">'+['Лиабро — Крит','Тералель — Защита','Король-коров — Лечение','Морт — Уклонение','Каменное Лицо — Контроль'].map((x,i)=>`<button class="frow" data-f="${i}"><b>${x.split(' — ')[0]}</b><span>${x.split(' — ')[1]}</span></button>`).join('')+'</div>');
$$('[data-home]').forEach(b=>b.onclick=home);$$('[data-roadmap]').forEach(b=>b.onclick=()=>show('roadmap'));
$$('.screen').forEach(x=>x.classList.remove('active'));$('#home').classList.add('active');setHomeZones();arenaZones();inventory();shop();games();
})();