/* Territory Game — Arena 1x1 tactical engine + skeletal combat animation */
(function(){
  'use strict';
  const S=()=>window.TerritoryStore?.state;const save=()=>window.TerritoryStore?.saveNow?.('arena');
  let battle=null;
  const $=(s,r=document)=>r.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const zones=[['head','Голова'],['chest','Грудь'],['waist','Пояс'],['legs','Ноги']];
  const botNames=['Эйрик','Хальвдан','Сигурд','Рагнар'];
  const classes=['duelist','berserker','tank','assassin'];
  function player(){const s=S(),ag=Math.max(1,Number(s?.agility)||5),max=Math.max(1,Number(s?.maxHp)||120),buff=s?.combatBuffs||{};return {id:'player',name:String(s?.profile?.displayName||s?.name||'Игрок'),level:Math.max(1,Number(s?.level)||1),hp:Math.max(0,Math.min(max,Number(s?.hp??max))),maxHp:max,attack:Math.max(1,Math.floor((Number(s?.strength)||5)+(Number(s?.bonusDamage)||0)+(Number(buff.attack)||0))),defense:Math.max(0,Number(s?.defense)||0)+(Number(buff.defense)||0),crit:Math.min(.5,(5+Math.floor(ag*.75))/100),dodge:Math.min(.35,(2+Math.floor(ag*.5))/100),speed:10+ag,class:'duelist'};}
  function bot(){const i=Math.floor(Math.random()*botNames.length),lvl=Math.max(1,(Number(S()?.level)||1)+Math.floor(Math.random()*2)-1),hp=90+lvl*12;return{id:'bot-'+Date.now(),name:botNames[i],level:lvl,hp,maxHp:hp,attack:10+lvl*2,defense:2+Math.floor(lvl/2),crit:.08,dodge:.06,speed:9+Math.floor(Math.random()*5),class:classes[i]};}
  function ensureRoot(){const modal=$('#arenaModal'),body=$('#arenaModalBody');if(!modal||!body)return null;return {modal,body};}
  function fighter(side,u){return `<div class="combat-fighter ${side}" data-fighter="${u.id}"><div class="fighter-name">${esc(u.name)} <small>Lv.${u.level}</small></div><div class="fighter-body"><div class="hero-head"><i></i></div><div class="hero-torso"></div><div class="hero-arm arm-back"></div><div class="hero-arm arm-front"><span class="weapon">${side==='player'?'⚔️':'🪓'}</span></div><div class="hero-leg leg-back"></div><div class="hero-leg leg-front"></div></div><div class="fighter-hp"><i style="width:100%"></i></div></div>`;}
  function view(){const root=ensureRoot();if(!root)return;const p=battle.player,b=battle.bot;root.body.innerHTML=`<div class="arena-battle" data-battle-root><div class="battle-scroll-scene"><div class="scene-ground"></div></div><div class="battle-flash" data-flash></div><div class="battle-header"><span>АРЕНА · 1×1</span><b>ХОД ${battle.turn}</b><span>Рейтинг ${S()?.arena?.rating||1000}</span></div><div class="battle-stage"><div class="fighter-wrap player-wrap">${fighter('player',p)}</div><div class="fighter-wrap bot-wrap">${fighter('bot',b)}</div><div class="damage-layer" data-damage-layer></div></div><div class="battle-status"><span data-status>Выбери зону удара</span><b>${Math.max(0,p.hp)} / ${p.maxHp} ❤️</b><b>${Math.max(0,b.hp)} / ${b.maxHp} ❤️</b></div><div class="zone-title">УДАР</div><div class="combat-zones attack-zones">${zones.map(z=>`<button data-attack-zone="${z[0]}">${z[1]}</button>`).join('')}</div><div class="zone-title">ЗАЩИТА</div><div class="combat-zones defense-zones">${zones.map(z=>`<button data-defense-zone="${z[0]}">${z[1]}</button>`).join('')}</div><div class="battle-actions"><button data-use-item>🧪 Эликсир</button><button data-surrender>Сдаться</button></div><div class="battle-log" data-log></div></div>`;root.modal.classList.add('show');root.modal.setAttribute('aria-hidden','false');animateEntry();updateBars();}
  function animateEntry(){requestAnimationFrame(()=>{$('.bot-wrap')?.classList.add('enter');$('.player-wrap')?.classList.add('run');});}
  function log(t){const el=$('[data-log]');if(el){const d=document.createElement('div');d.textContent=t;el.prepend(d);}}
  function popup(text,crit=false,side='bot'){const layer=$('[data-damage-layer]');if(!layer)return;const el=document.createElement('div');el.className='damage-popup '+(crit?'critical':'')+' '+side;el.innerHTML=crit?'💥 '+esc(text):esc(text);layer.appendChild(el);setTimeout(()=>el.remove(),850);}
  function updateBars(){if(!battle)return;for(const u of [battle.player,battle.bot]){const el=$(`[data-fighter="${u.id}"] .fighter-hp i`);if(el)el.style.width=Math.max(0,u.hp/u.maxHp*100)+'%';}const p=battle.player,b=battle.bot;const bs=$('.battle-status');if(bs){const vals=bs.querySelectorAll('b');if(vals[0])vals[0].textContent=`${Math.max(0,p.hp)} / ${p.maxHp} ❤️`;if(vals[1])vals[1].textContent=`${Math.max(0,b.hp)} / ${b.maxHp} ❤️`;}}
  function anim(side,type){const el=$(`.fighter-wrap.${side}-wrap`);if(!el)return;el.classList.remove('attack','hit','dodge','crit');void el.offsetWidth;el.classList.add(type);setTimeout(()=>el.classList.remove(type),type==='attack'?520:420);}
  function hitTarget(target,zone,attacker){const raw=Math.max(1,attacker.attack+Math.floor(Math.random()*7)-3);const crit=Math.random()<attacker.crit;const dmg=Math.max(1,raw*(crit?2:1)-Math.floor(target.defense*.35));target.hp=Math.max(0,target.hp-dmg);return{dmg,crit};}
  function botTurn(){if(!battle||battle.bot.hp<=0)return;const p=battle.player,zone=zones[Math.floor(Math.random()*zones.length)][0];const defense=battle.playerDefense||'';setTimeout(()=>{if(Math.random()<p.dodge){anim('player','dodge');popup('Уклонение 💨',false,'player');log(`${battle.bot.name}: промах — уклонение`);battle.playerDefense='';nextReady();return;}anim('bot','attack');setTimeout(()=>{const r=hitTarget(p,zone,battle.bot);anim('player',r.crit?'hit':'hit');popup('-'+r.dmg,r.crit,'player');log(`${battle.bot.name} атакует: -${r.dmg}`);updateBars();battle.playerDefense='';if(p.hp<=0)return finish(false);nextReady();},260);},420);}
  function nextReady(){if(!battle)return;const st=$('[data-status]');if(st)st.textContent='Твой ход — выбери зону удара';document.querySelectorAll('[data-attack-zone],[data-defense-zone]').forEach(x=>x.disabled=false);}
  function playerAttack(zone){if(!battle||battle.busy)return;battle.busy=true;document.querySelectorAll('[data-attack-zone],[data-defense-zone]').forEach(x=>x.disabled=true);const p=battle.player,b=battle.bot;anim('player','attack');setTimeout(()=>{if(Math.random()<b.dodge){anim('bot','dodge');popup('Уклонение 💨',false,'bot');log(`${b.name}: уклонился`);battle.turn++;battle.busy=false;setTimeout(botTurn,350);return;}const r=hitTarget(b,zone,p);popup('-'+r.dmg,r.crit,'bot');anim('bot',r.crit?'hit':'hit');if(r.crit){const f=$('[data-flash]');f?.classList.add('show');setTimeout(()=>f?.classList.remove('show'),150);}log(`Удар в ${zones.find(z=>z[0]===zone)?.[1]||zone}: -${r.dmg}${r.crit?' · КРИТ':''}`);updateBars();if(b.hp<=0){finish(true);return;}battle.turn++;setTimeout(()=>{battle.busy=false;botTurn();},450);},300);}
  function useItem(){const s=S();const ids=['elixir_hp','elixir_energy','elixir_attack','elixir_guard'];const id=ids.find(x=>Number(s?.consumables?.[x]||0)>0);if(!id||!window.CombatItems?.use)return;window.CombatItems.use(id);log('Использован '+window.CombatItems.CATALOG[id].name);updateBars();}
  function finish(win){const s=S();const a=Object.assign({},s.arena||{});a.battles=(Number(a.battles)||0)+1;if(win){a.wins=(Number(a.wins)||0)+1;a.rating=(Number(a.rating)||1000)+18;s.coins+=75;s.exp+=15;}else{a.losses=(Number(a.losses)||0)+1;a.rating=Math.max(0,(Number(a.rating)||1000)-14);s.exp+=5;}a.history=Array.isArray(a.history)?a.history.slice(-19):[];a.history.unshift({win,date:Date.now(),opponent:battle.bot.name});s.arena=a;s.hp=Math.max(0,Math.min(s.maxHp,battle.player.hp));s.combatBuffs={attack:0,defense:0};save();const root=ensureRoot();if(!root)return;root.body.innerHTML=`<div class="arena-result"><div>${win?'🏆':'💀'}</div><h1>${win?'ПОБЕДА':'ПОРАЖЕНИЕ'}</h1><p>${esc(battle.bot.name)} · ${win?'+75 🪙 · +15 XP':'+5 XP'}</p><button class="arena-main" data-restart>ЕЩЁ БОЙ</button><button class="arena-secondary" data-close-arena>ВЕРНУТЬСЯ</button></div>`;battle=null;}
  function open(){const root=ensureRoot();if(!root)return;if(battle)return;const p=player(),b=bot();battle={player:p,bot:b,turn:1,busy:false,playerDefense:''};view();}
  function close(){const root=ensureRoot();if(!root)return;root.modal.classList.remove('show');root.modal.setAttribute('aria-hidden','true');battle=null;}
  document.addEventListener('click',e=>{const az=e.target.closest?.('[data-attack-zone]');if(az)playerAttack(az.dataset.attackZone);const dz=e.target.closest?.('[data-defense-zone]');if(dz&&battle){battle.playerDefense=dz.dataset.defenseZone;document.querySelectorAll('[data-defense-zone]').forEach(x=>x.classList.remove('selected'));dz.classList.add('selected');const st=$('[data-status]');if(st)st.textContent='Защита: '+dz.textContent;}
    if(e.target.closest?.('[data-use-item]'))useItem();if(e.target.closest?.('[data-surrender]'))finish(false);if(e.target.closest?.('[data-close-arena]'))close();if(e.target.closest?.('[data-restart]')){battle=null;open();}
  });
  document.getElementById('arenaClose')?.addEventListener('click',close);
  window.ArenaGame={open,close};
})();
