/* TERITORY ARENA v32 — Stage 1: unified 1×1 Arena Engine, 4 combat zones
   HOME artwork and frozen bottom navigation 42–48 are untouched.
   TerritoryStore is the single source of player state.
*/
(function(){
'use strict';
if(!window.__territoryCombatItemsLoader){window.__territoryCombatItemsLoader=true;const s=document.createElement('script');s.src='combat-items.js?v=2';document.head.appendChild(s);}
const ZONES=[['head','Голова'],['chest','Грудь'],['waist','Пояс'],['legs','Ноги']];
const CLASSES={tank:{name:'Танк',icon:'🛡️',hp:150,atk:.86,def:1.30,crit:.06,dodge:.04},berserker:{name:'Берсерк',icon:'🪓',hp:112,atk:1.30,def:.84,crit:.17,dodge:.07},assassin:{name:'Ассасин',icon:'🗡️',hp:98,atk:1.20,def:.80,crit:.24,dodge:.18},duelist:{name:'Дуэлянт',icon:'⚔️',hp:118,atk:1.08,def:1.02,crit:.14,dodge:.12},support:{name:'Поддержка',icon:'✨',hp:128,atk:.88,def:1.06,crit:.09,dodge:.08}};
const NAMES=['Michael Carter','Валера Соколов','James Anderson','Андрей Кузнецов','Robert Mitchell','Олег Морозов','David Thompson','Daniel Brooks','Сергей Волков','Christopher Reed','Максим Орлов','Andrew Walker','Thomas Bennett','Дмитрий Павлов','Kevin Parker','Matthew Collins','Виктор Смирнов','Ryan Cooper','Jason Morgan','Никита Ковалёв'];
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const state=()=>window.TerritoryStore?.state||{};
const save=()=>{try{window.TerritoryStore?.saveNow?.('arena')}catch(_){}};
let battle=null,seq=0;
function player(){const s=state(),p=s.profile||{},level=Math.max(1,Number(s.level)||1),agility=Math.max(1,Number(s.agility)||5),hp=Math.max(1,Number(s.maxHp)||120),buff=s.combatBuffs||{};return{id:'player',player:true,name:String(p.displayName||s.name||'Игрок'),level,class:String(s.heroClass||'duelist'),rating:Number(s.arena?.rating||1000),hp:Math.min(hp,Math.max(0,Number(s.hp??hp))),maxHp:hp,attack:Math.max(1,Math.floor(Number(s.strength||5)+Number(s.bonusDamage||0)+Number(buff.attack||0))),defense:Math.max(0,Number(s.defense||0)+Number(buff.defense||0)),crit:Math.min(.5,(5+Math.floor(agility*.75))/100),dodge:Math.min(.4,(2+Math.floor(agility*.5))/100),speed:10+agility};}
function opponent(){const keys=Object.keys(CLASSES),k=keys[rnd(0,keys.length-1)],c=CLASSES[k],level=Math.max(1,Number(state().level||1)+rnd(-1,2));return{id:'op-'+Date.now(),name:NAMES[rnd(0,NAMES.length-1)],level,class:k,rating:Math.max(0,Number(state().arena?.rating||1000)+rnd(-180,180)),hp:c.hp+level*4,maxHp:c.hp+level*4,style:['Агрессивный','Баланс','Защитный','Контратакующий'][rnd(0,3)]};}
function shell(){const m=$('#arenaModal');if(!m)return null;m.style.display='flex';m.style.pointerEvents='auto';m.classList.add('show');m.setAttribute('aria-hidden','false');return m;}
function close(){const m=$('#arenaModal');if(m){m.classList.remove('show');m.style.display='none';m.style.pointerEvents='none';m.setAttribute('aria-hidden','true')}battle=null}
window.closeArenaModal=close;
window.arenaToast=t=>{const x=$('#arenaToast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window._at);window._at=setTimeout(()=>x.classList.remove('show'),1800)};
function frame(title,body){shell();const h=$('#arenaModalTitle'),m=$('#arenaModalBody');if(h)h.textContent=title;if(m)m.innerHTML=`<div class="arena-v32">${body}</div>`;const b=$('#arenaClose');if(b)b.onclick=close;}
function ensureCSS(){if($('#arenaStage1CSS'))return;const s=document.createElement('style');s.id='arenaStage1CSS';s.textContent=`.arena-v32{padding:12px;color:#fff;font-family:Arial,sans-serif}.a31-card{background:#14202b;border:1px solid #3b4b5a;border-radius:14px;padding:12px;margin:8px 0}.a31-top{display:flex;justify-content:space-between;gap:8px}.a31-muted{color:#9cabb8;font-size:11px}.a31-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.a31-btn{width:100%;min-height:42px;border:1px solid #526474;border-radius:10px;background:#1b2a38;color:#fff;font-weight:800}.a31-btn.sel{border-color:#55b7ff;background:#25445a}.a31-main{width:100%;min-height:48px;border:0;border-radius:12px;background:#2678b8;color:#fff;font-weight:900}.a31-unit{display:flex;align-items:center;gap:10px}.a31-avatar{width:48px;height:48px;border-radius:12px;background:#0d1720;display:grid;place-items:center;font-size:25px}.a31-hp{height:7px;background:#071018;border-radius:8px;overflow:hidden;margin-top:6px}.a31-hp i{display:block;height:100%;background:#5bc46b}.a31-log{max-height:150px;overflow:auto;font-size:11px;color:#c8d3dc}.a31-result{text-align:center;padding:12px}.a31-result h1{margin:8px 0}`;document.head.appendChild(s);}
function stats(u){if(u.player)return{atk:u.attack,def:u.defense,crit:u.crit,dodge:u.dodge};const c=CLASSES[u.class]||CLASSES.duelist;return{atk:Math.round(11+c.atk*(6+u.level*.75)),def:Math.round(c.def*(2+u.level*.36)),crit:c.crit,dodge:c.dodge};}
function ai(u){let attack=ZONES[rnd(0,ZONES.length-1)][0],def=[];if(u.style==='Защитный')def=['chest','waist'];else if(u.style==='Агрессивный')def=['head','legs'];else def=ZONES.slice().sort(()=>Math.random()-.5).slice(0,2).map(x=>x[0]);return{attack,def};}
function rank(r){if(r<900)return'Бронза';if(r<1100)return'Серебро';if(r<1300)return'Золото';if(r<1500)return'Платина';return'Алмаз';}
function unit(u){const c=CLASSES[u.class]||CLASSES.duelist,pct=Math.max(0,Math.min(100,u.hp/u.maxHp*100));return`<div class="a31-unit"><div class="a31-avatar">${c.icon}</div><div style="flex:1;min-width:0"><b>${esc(u.name)}</b><div class="a31-muted">ур. ${u.level} · ${c.name} · ${u.rating||0}</div><div class="a31-hp"><i style="width:${pct}%"></i></div></div><b>${Math.ceil(Math.max(0,u.hp))}</b></div>`;}
function arenaHome(){const p=player(),a=state().arena||{},energy=Number(state().energy??100);frame('⚔️ Арена',`<div class="a31-card"><div class="a31-top"><div><b>1 × 1 · ARENA ENGINE</b><div class="a31-muted">Игрок против одного соперника</div></div><b>⚡ ${energy}/${Number(state().maxEnergy||200)}</b></div></div><div class="a31-card">${unit(p)}<div class="a31-muted" style="margin-top:8px">🏆 ${Number(a.rating||1000)} · ${rank(Number(a.rating||1000))} · побед ${Number(a.wins||0)} · поражений ${Number(a.losses||0)}</div>${(Number(state().combatBuffs?.attack||0)||Number(state().combatBuffs?.defense||0))?`<div class="a31-muted" style="margin-top:7px">🔥 Боевые бонусы: +${Number(state().combatBuffs?.attack||0)} урон · 🛡️ +${Number(state().combatBuffs?.defense||0)} защита</div>`:''}</div><div class="a31-card"><b>Боевой режим</b><p class="a31-muted">Стоимость входа: 10 энергии. Соперник получает полный профиль и боевые характеристики.</p><button class="a31-main" id="a31Start">⚔️ НАЙТИ СОПЕРНИКА</button></div><div class="a31-card a31-muted">3 × 3 и CHAOS подключим после стабилизации 1 × 1.</div>`);$('#a31Start').onclick=startMatch;}
function startMatch(){const s=state();if(Number(s.energy??0)<10){arenaToast('⚡ Нужно 10 энергии');return}battle={id:Date.now(),player:player(),enemy:opponent(),round:1,attack:null,def:[],log:[],locked:false};seq=0;renderBattle();}
function renderBattle(){if(!battle)return;const b=battle,e=b.enemy;frame('⚔️ 1 × 1',`<div class="a31-top a31-muted"><span>Бой #${String(b.id).slice(-6)}</span><span>Раунд ${b.round}</span><span>Ход ${seq}</span></div><div class="a31-card">${unit(b.player)}</div><div style="text-align:center;font-weight:900">VS</div><div class="a31-card">${unit(e)}</div><div class="a31-card"><b>🎯 Куда атаковать?</b><div class="a31-grid" style="margin-top:8px">${ZONES.map(z=>`<button class="a31-btn ${b.attack===z[0]?'sel':''}" data-a="${z[0]}">${z[1]}</button>`).join('')}</div></div><div class="a31-card"><b>🛡️ Что защищать? Выбери 2</b><div class="a31-grid" style="margin-top:8px">${ZONES.map(z=>`<button class="a31-btn ${b.def.includes(z[0])?'sel':''}" data-d="${z[0]}">${z[1]}</button>`).join('')}</div></div><button class="a31-main" id="a31Hit">⚔️ АТАКА</button><div class="a31-card a31-log">${b.log.slice(-8).map(x=>`<div>${esc(x)}</div>`).join('')||'Выбери цель и 2 зоны защиты.'}</div>`);$$('[data-a]').forEach(x=>x.onclick=()=>{b.attack=x.dataset.a;renderBattle()});$$('[data-d]').forEach(x=>x.onclick=()=>{const z=x.dataset.d;if(b.def.includes(z))b.def=b.def.filter(v=>v!==z);else if(b.def.length<2)b.def.push(z);renderBattle()});$('#a31Hit').onclick=playerTurn;}
function playerTurn(){const b=battle;if(!b||b.locked)return;if(!b.attack||b.def.length!==2){arenaToast('🎯 Выбери атаку и 2 зоны защиты');return}b.locked=true;seq++;const m=stats(b.player),target=b.enemy,plan=ai(target);let msg='';if(plan.def.includes(b.attack))msg=`🛡️ ${target.name} заблокировал «${ZONES.find(z=>z[0]===b.attack)[1]}»`;else if(Math.random()<.07)msg=`💨 ${b.player.name} промахнулся`;else{let dmg=Math.max(3,Math.round(m.atk*(b.attack==='head'?1.18:b.attack==='legs'?.95:1)-stats(target).def));const crit=Math.random()<m.crit*(b.attack==='head'?1.3:1);if(crit)dmg=Math.round(dmg*1.6);target.hp=Math.max(0,target.hp-dmg);msg=`⚔️ ${b.player.name} → ${target.name}: −${dmg} HP${crit?' 💥 КРИТ':''}`;}b.log.push(msg);if(target.hp<=0){finish(true);return}renderBattle();setTimeout(enemyTurn,650);}
function enemyTurn(){const b=battle;if(!b)return;const p=b.player,e=b.enemy,m=stats(e),plan=ai(e);let msg='';if(b.def.includes(plan.attack))msg=`🛡️ ${p.name} заблокировал атаку «${ZONES.find(z=>z[0]===plan.attack)[1]}»`;else if(Math.random()<stats(p).dodge*.5)msg=`💨 ${p.name} увернулся от ${e.name}`;else{let dmg=Math.max(2,Math.round(m.atk-stats(p).def*.45));if(Math.random()<m.crit)dmg=Math.round(dmg*1.45);p.hp=Math.max(0,p.hp-dmg);msg=`☠️ ${e.name} → ${p.name}: −${dmg} HP`;}b.log.push(msg);b.round++;b.attack=null;b.def=[];b.locked=false;if(p.hp<=0){finish(false);return}renderBattle();}
function finish(win){const b=battle;if(!b)return;const s=state(),a={...(s.arena||{})},delta=win?18:-14,cost=10;a.rating=Math.max(0,Math.floor(Number(a.rating||1000)+delta));a.wins=Math.max(0,Math.floor(Number(a.wins||0)+(win?1:0)));a.losses=Math.max(0,Math.floor(Number(a.losses||0)+(win?0:1)));a.battles=a.wins+a.losses;a.history=Array.isArray(a.history)?a.history.slice(-29):[];a.history.push({mode:'1v1',opponent:b.enemy.name,win,delta,date:new Date().toLocaleString('ru-RU')});s.arena=a;s.hp=Math.max(0,Math.min(Number(s.maxHp||120),Math.floor(b.player.hp)));s.energy=Math.max(0,Number(s.energy||0)-cost);s.exp=Math.max(0,Number(s.exp||0)+(win?15:5));if(win)s.coins=Math.max(0,Number(s.coins||0)+75);s.combatBuffs={attack:0,defense:0};save();frame(win?'🏆 ПОБЕДА':'💀 ПОРАЖЕНИЕ',`<div class="a31-result"><div style="font-size:48px">${win?'🏆':'💀'}</div><h1>${win?'Победа!':'Поражение'}</h1><p>${win?'+75 🪙 · +15 XP':' +5 XP'} · ${win?'+18':'−14'} рейтинга</p><div class="a31-card">🏆 Рейтинг: <b>${a.rating}</b><br>❤️ HP после боя: <b>${s.hp}/${s.maxHp}</b><br>⚡ Энергия: <b>${s.energy}</b></div><button class="a31-main" id="a31Again">⚔️ Ещё бой</button><button class="a31-btn" id="a31Back" style="margin-top:8px">🏟️ В арену</button></div>`);$('#a31Again').onclick=arenaHome;$('#a31Back').onclick=arenaHome;battle=null;}
function openArena(){ensureCSS();arenaHome();}
window.openBattle=openArena;
function direct(e){const hz=e.target.closest?.('.hz'),screen=e.target.closest?.('[data-screen]');const arena=hz&&(hz.dataset.hz==='arena'||hz.dataset.hz==='battle'),bottom=screen&&screen.dataset.screen==='arena';if(!arena&&!bottom)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openArena();}
document.addEventListener('click',direct,true);document.addEventListener('pointerdown',direct,true);document.addEventListener('touchstart',direct,{capture:true,passive:false});
document.addEventListener('DOMContentLoaded',()=>$('#arenaModal')?.addEventListener('click',e=>{if(e.target.id==='arenaModal')close()}));
})();
/* TERITORY LAVKA v1 — shared shop catalog -> inventory -> quantity -> use.
   Added as a layer over the existing app. HOME and frozen navigation are untouched. */
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const catalog=[
 {id:'elixir_hp',name:'Зелье HP',icon:'🧪',price:80,max:5,effect:'+30 HP',desc:'Восстанавливает здоровье героя.'},
 {id:'elixir_energy',name:'Зелье энергии',icon:'🔵',price:70,max:5,effect:'+25 энергии',desc:'Восстанавливает энергию героя.'},
 {id:'elixir_guard',name:'Защитный эликсир',icon:'🛡️',price:120,max:5,effect:'+5 защиты',desc:'Даёт +5 защиты для следующего боя.'},
 {id:'elixir_attack',name:'Боевой эликсир',icon:'🔥',price:120,max:5,effect:'+5 урона',desc:'Даёт +5 урона для следующего боя.'}
];
const st=()=>window.TerritoryStore?.state||{};
const save=()=>{try{window.TerritoryStore?.saveNow?.('lavka')}catch(_){} };
function qty(id){const row=(Array.isArray(st().consumables)?st().consumables:[]).find(x=>x&&x.id===id);return Math.max(0,Math.floor(Number(row?.quantity)||0));}
function setQty(id,n){const s=st();s.consumables=Array.isArray(s.consumables)?s.consumables:[];let row=s.consumables.find(x=>x&&x.id===id);n=Math.max(0,Math.min(catalog.find(x=>x.id===id)?.max||99,Math.floor(Number(n)||0)));if(!row&&n>0){row={id,quantity:n};s.consumables.push(row)}else if(row){row.quantity=n;if(n===0)s.consumables=s.consumables.filter(x=>x!==row)}save();}
function buy(id){const item=catalog.find(x=>x.id===id);if(!item)return;const q=qty(id);if(q>=item.max){window.arenaToast?.('📦 Запас уже полный');return}const cost=Math.floor(item.price*(Number(st().merchantRep||0)>=5?.9:Number(st().merchantRep||0)>=2?.95:1));if(Number(st().coins||0)<cost){window.arenaToast?.('🪙 Не хватает монет');return}st().coins=Number(st().coins||0)-cost;setQty(id,q+1);st().merchantRep=Math.max(0,Number(st().merchantRep||0)+1);save();window.arenaToast?.(`${item.icon} ${item.name} · теперь ×${q+1}`);renderAll();}
function use(id){const item=catalog.find(x=>x.id===id);if(!item||qty(id)<=0)return;const s=st();if(id==='elixir_hp'){const max=Number(s.maxHp||120),before=Number(s.hp||0);if(before>=max){window.arenaToast?.('❤️ Здоровье уже полное');return}s.hp=Math.min(max,before+30)}
else if(id==='elixir_energy'){const max=Number(s.maxEnergy||200),before=Number(s.energy||0);if(before>=max){window.arenaToast?.('⚡ Энергия уже полная');return}s.energy=Math.min(max,before+25)}
else if(id==='elixir_guard'){s.combatBuffs={...(s.combatBuffs||{}),defense:Number(s.combatBuffs?.defense||0)+5}}
else if(id==='elixir_attack'){s.combatBuffs={...(s.combatBuffs||{}),attack:Number(s.combatBuffs?.attack||0)+5}}
setQty(id,qty(id)-1);save();window.arenaToast?.(`${item.icon} Использовано: ${item.name}`);renderAll();}
function injectCSS(){if($('#lavkaLayerCSS'))return;const x=document.createElement('style');x.id='lavkaLayerCSS';x.textContent=`
.lavka-consumables{margin-top:14px}.lavka-title{display:flex;justify-content:space-between;align-items:end;margin:14px 0 8px}.lavka-title b{font-size:14px}.lavka-title small{font-size:10px;color:#9eacba}.lavka-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.lavka-card{background:#17242f;border:1px solid #40515f;border-radius:13px;padding:10px;color:#fff;box-sizing:border-box}.lavka-card .lavka-icon{font-size:31px}.lavka-card b{display:block;margin-top:4px;font-size:12px}.lavka-card span{display:block;color:#aebbc6;font-size:10px;line-height:1.3;margin-top:3px;min-height:26px}.lavka-card small{display:block;margin-top:6px;color:#d5dee5;font-weight:800}.lavka-card button{width:100%;margin-top:8px;min-height:34px;border:0;border-radius:9px;background:#b98b3e;color:#101820;font-weight:900;font-size:10px}.lavka-card button.use{background:#29465a;color:#fff}.lavka-empty{padding:10px;border:1px dashed #40515f;border-radius:11px;color:#9eacba;font-size:11px;grid-column:1/-1}
#market .lavka-consumables .item{min-width:0}
@media(max-width:360px){.lavka-grid{grid-template-columns:1fr}}
` ;document.head.appendChild(x)}
function renderMarket(){const grid=$('#shopGrid');if(!grid)return;const old=grid.innerHTML;const items=catalog.map(x=>{const q=qty(x.id),cost=Math.floor(x.price*(Number(st().merchantRep||0)>=5?.9:Number(st().merchantRep||0)>=2?.95:1));return `<div class="item lavka-item"><div class="pic">${x.icon}</div><b>${x.name}</b><span>${x.effect}</span><small>В запасе: ×${q} / ${x.max}</small><button data-lavka-buy="${x.id}">${cost} 🪙 · КУПИТЬ</button></div>`}).join('');grid.innerHTML=old+`<div class="lavka-consumables"><div class="lavka-title"><b>ЭЛИКСИРЫ И РАСХОДНИКИ</b><small>Покупка сразу попадёт в инвентарь</small></div><div class="lavka-grid">${items}</div></div>`}
function renderInventory(){const grid=$('#inventoryGrid');if(!grid)return;const oldItems=Array.isArray(st().inventory)?st().inventory:[];const generic=oldItems.map((x,i)=>{const icon=typeof x==='object'?String(x.icon||'📦'):String(x);return `<div class="item"><div class="pic">${icon}</div><b>Предмет ${i+1}</b><span>Предмет</span></div>`}).join('');const cards=catalog.map(x=>{const q=qty(x.id);return `<div class="item lavka-item"><div class="pic">${x.icon}</div><b>${x.name}</b><span>${x.effect}</span><strong>Количество · ×${q}</strong>${q?`<button type="button" data-lavka-use="${x.id}">ИСПОЛЬЗОВАТЬ</button>`:`<button type="button" data-screen="market">В ЛАВКУ</button>`}</div>`}).join('');grid.innerHTML=`<div class="lavka-title" style="grid-column:1/-1"><b>РАСХОДНИКИ</b><small>Общие для RPG и боёв</small></div>${cards}${generic}`}
function rename(){document.querySelectorAll('[data-screen="market"]').forEach(b=>{const s=b.querySelector('span');if(s)s.textContent='Лавка'});document.querySelectorAll('#market h2').forEach(x=>x.textContent='ЛАВКА СНАРЯЖЕНИЯ');document.querySelectorAll('#market .merchant-stock-head b').forEach(x=>x.textContent='ТОВАРЫ ЛАВКИ');document.querySelectorAll('.hs-market').forEach(x=>x.setAttribute('aria-label','Лавка'));}
function renderAll(){rename();renderMarket();renderInventory();}
function boot(){injectCSS();rename();const oldRender=window.render;if(typeof oldRender==='function'&&!window.__lavkaWrapped){window.__lavkaWrapped=true;window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(renderAll,0);return r};}document.addEventListener('click',e=>{const buy=e.target.closest?.('[data-lavka-buy]');if(buy){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();buyNow(buy.dataset.lavkaBuy);return}const useBtn=e.target.closest?.('[data-lavka-use]');if(useBtn){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();use(useBtn.dataset.lavkaUse);return}},true);setTimeout(renderAll,0);}
function buyNow(id){buy(id)}
window.TerritoryLavka={catalog,buy,use,quantity:qty,render:renderAll};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
