/* Territory v140 — Arena tactical mobile prototype.
   Local/client simulation: 1x1, chaos, group; 3-minute lobby; 4 attack zones; exactly 2 defense zones. */
(()=>{
const A=[['head','Голова','🎯'],['chest','Грудь','🫀'],['waist','Пояс','🛡️'],['legs','Ноги','🦵']];
const D=[['head','Голова','⬆️'],['chest','Грудь','🛡️'],['waist','Пояс','↔️'],['legs','Ноги','⬇️']];
const M=[
{id:'duel',title:'1×1 бой',icon:'⚔️',desc:'Один против одного. Ожидание — 3 минуты.'},
{id:'chaos',title:'Хаотичный бой',icon:'🎲',desc:'Все входят в одну комнату, затем команды распределяются случайно.'},
{id:'group',title:'Групповой бой',icon:'👥',desc:'Выбор команды 1 или 2. До 20 игроков.'}];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const st=()=>{try{return state}catch(e){return {}}},modal=()=>document.getElementById('arenaModal'),body=()=>document.getElementById('arenaModalBody');
let stats={wins:0,losses:0,battles:0,history:[]},lobby=null,battle=null,lt=null,bt=null;
try{stats={...stats,...JSON.parse(localStorage.getItem('territory_arena_v140')||'{}')}}catch(e){}
function saveStats(){localStorage.setItem('territory_arena_v140',JSON.stringify(stats))}
function show(t,h){const m=modal(),b=body();if(!m||!b)return;document.getElementById('arenaModalTitle').textContent=t;b.innerHTML=h;m.classList.add('show');m.setAttribute('aria-hidden','false')}
function close(){clearInterval(lt);clearInterval(bt);lt=bt=null;lobby=battle=null;const m=modal();if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}}
window.closeArenaModal=close;
window.arenaToast=t=>{const x=document.getElementById('arenaToast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__arenaToast);window.__arenaToast=setTimeout(()=>x.classList.remove('show'),1600)};
const name=()=>String(st().name||'SSS'),level=()=>Number(st().level||1);
function home(){
clearInterval(lt);clearInterval(bt);lobby=battle=null;
const hist=(stats.history||[]).slice(-5).reverse().map(h=>`<div class="arena140-history-row"><span>${h.win?'🏆':'💀'}</span><span>${esc(h.mode)}</span><span>${esc(h.result)}</span></div>`).join('');
show('⚔️ Арена',`<div class="arena140"><section class="arena140-hero"><div><div class="arena140-kicker">SDOLARS · ARENA</div><h2>Бой начинается здесь</h2><p>Тактический бой по ходам. Выбирай атаку и две зоны защиты.</p></div><div class="arena140-stat"><b>${stats.wins||0}</b><span>побед</span></div></section><section class="arena140-modes">${M.map(m=>`<button class="arena140-mode" data-mode="${m.id}"><span class="mode-icon">${m.icon}</span><span><b>${m.title}</b><small>${m.desc}</small></span><strong>›</strong></button>`).join('')}</section><section class="arena140-rules"><b>Правила Arena</b><div><span>⏱️ 3:00</span><span>👥 до 20</span><span>🎯 4 атаки</span><span>🛡️ 4 защиты</span></div><p>Вышедший игрок не может повторно войти в этот же бой.</p></section><section class="arena140-history"><div class="arena140-section-head"><b>Последние бои</b><span>${stats.battles||0}</span></div>${hist||'<div class="arena140-empty">Пока нет завершённых боёв.</div>'}</section></div>`);
body().querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>lobbyStart(b.dataset.mode))}
function lobbyStart(mode){lobby={mode,endsAt:Date.now()+180000,started:false,left:false,players:[{name:name(),level:level(),team:mode==='group'?1:null,owner:true}]};lobbyView()}
function add(){if(!lobby||lobby.started)return;const max=lobby.mode==='duel'?2:20;if(lobby.players.length>=max)return arenaToast('Комната заполнена');const n=['Варг','Рагнар','Стальной Волк','Наёмник','Берсерк','Охотник','Гвардеец'];const i=lobby.players.length-1;lobby.players.push({name:n[i%n.length]+' '+(i+2),level:Math.max(1,level()+Math.floor(Math.random()*3)-1),team:lobby.mode==='group'?(i%2)+1:null,bot:true});lobbyView()}
function lobbyView(){clearInterval(lt);if(!lobby)return;const m=M.find(x=>x.id===lobby.mode),r=Math.max(0,lobby.endsAt-Date.now()),mm=String(Math.floor(r/60000)).padStart(2,'0'),ss=String(Math.floor(r/1000)%60).padStart(2,'0'),max=lobby.mode==='duel'?2:20;
const ps=lobby.players.map(p=>`<div class="arena140-player"><span class="avatar">${p.bot?'⚔️':'🧔'}</span><span><b>${esc(p.name)}</b><small>ур. ${p.level}${p.owner?' · создатель':''}</small></span>${lobby.mode==='group'?`<em class="team team-${p.team}">Команда ${p.team}</em>`:''}</div>`).join('');
show(`${m.icon} ${m.title}`,`<div class="arena140"><section class="arena140-lobby-head"><div><span class="arena140-kicker">КОМНАТА БОЯ</span><h2>Ожидание игроков</h2><p>${esc(m.desc)}</p></div><div class="arena140-countdown"><small>Автостарт</small><b>${mm}:${ss}</b></div></section><section class="arena140-lobby-card"><div class="arena140-section-head"><b>Игроки</b><span>${lobby.players.length}/${max}</span></div><div class="arena140-players">${ps}</div></section>${lobby.mode==='group'?`<section class="arena140-team-choice"><b>Твоя команда</b><div><button data-team="1" class="${lobby.players[0].team===1?'selected':''}">⚔️ Команда 1</button><button data-team="2" class="${lobby.players[0].team===2?'selected':''}">🛡️ Команда 2</button></div></section>`:''}<section class="arena140-actions"><button class="arena140-secondary" data-add>＋ Добавить игрока для теста</button><button class="arena140-primary" data-start ${lobby.players.length>1?'':'disabled'}>⚔️ Начать сейчас</button><button class="arena140-leave" data-leave>Выйти из комнаты</button></section><p class="arena140-note">Создатель запускает таймер 3:00. После окончания бой стартует автоматически.</p></div>`);
body().querySelector('[data-add]')?.addEventListener('click',add);body().querySelector('[data-start]')?.addEventListener('click',battleStart);body().querySelector('[data-leave]')?.addEventListener('click',()=>{lobby.left=true;clearInterval(lt);arenaToast('Ты вышел. Повторный вход запрещён.');setTimeout(home,500)});
body().querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{lobby.players[0].team=+b.dataset.team;lobbyView()});
lt=setInterval(()=>{if(!lobby)return;if(Date.now()>=lobby.endsAt){clearInterval(lt);battleStart()}else lobbyView()},1000)}
function battleStart(){if(!lobby||lobby.started||lobby.left||lobby.players.length<2){if(lobby&&lobby.players.length<2)arenaToast('Нужно минимум 2 игрока');return}if(lobby.mode==='chaos'){lobby.players.forEach((p,i)=>p.team=(i%2)+1)}lobby.started=true;clearInterval(lt);battle={round:1,playerHp:+(st().hp||120),maxHp:+(st().maxHp||120),enemyHp:120,maxEnemyHp:120,attack:null,def:[],endsAt:Date.now()+600000,log:['⚔️ Бой начался.']};battleView()}
function battleView(){clearInterval(bt);if(!battle)return;const r=Math.max(0,battle.endsAt-Date.now()),mm=String(Math.floor(r/60000)).padStart(2,'0'),ss=String(Math.floor(r/1000)%60).padStart(2,'0'),p=Math.max(0,battle.playerHp/battle.maxHp*100),e=Math.max(0,battle.enemyHp/battle.maxEnemyHp*100);
const az=A.map(z=>`<button class="arena140-zone ${battle.attack===z[0]?'selected':''}" data-a="${z[0]}"><i>${z[2]}</i><span>${z[1]}</span></button>`).join(''),dz=D.map(z=>`<button class="arena140-zone ${battle.def.includes(z[0])?'selected defense':''}" data-d="${z[0]}"><i>${z[2]}</i><span>${z[1]}</span></button>`).join('');
show('⚔️ Arena · бой',`<div class="arena140 arena140-combat"><section class="arena140-fighters"><div class="arena140-fighter"><div class="big-avatar">🧔</div><b>${esc(name())}</b><small>ур. ${level()}</small><div class="arena140-hp"><i style="width:${p}%"></i></div><span>${Math.round(battle.playerHp)} / ${battle.maxHp} HP</span></div><div class="arena140-vs">VS</div><div class="arena140-fighter enemy"><div class="big-avatar">⚔️</div><b>Противник</b><small>отряд</small><div class="arena140-hp"><i style="width:${e}%"></i></div><span>${Math.round(battle.enemyHp)} / ${battle.maxEnemyHp} HP</span></div></section><section class="arena140-combat-top"><span>Раунд <b>${battle.round}</b></span><span>⏱️ <b>${mm}:${ss}</b></span><span>👥 ${lobby?.players.length||2}</span></section><section class="arena140-select"><div class="arena140-step"><b>1. Атака</b><small>Выбери одну из 4 зон</small></div><div class="arena140-zones">${az}</div><div class="arena140-step"><b>2. Защита</b><small>Выбери ровно две зоны</small></div><div class="arena140-zones">${dz}</div><button class="arena140-hit" data-hit ${battle.attack&&battle.def.length===2?'':'disabled'}>⚔️ ПОДТВЕРДИТЬ ХОД</button></section><section class="arena140-log"><div class="arena140-log-head"><b>Боевой журнал</b><button data-collapse>Свернуть</button></div><div class="arena140-log-body">${battle.log.slice(-10).map(x=>`<div>${esc(x)}</div>`).join('')}</div></section><section class="arena140-finish"><button data-finish>Завершить бой</button><button data-extend>Продлить +5 мин</button></section></div>`);
body().querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{battle.attack=b.dataset.a;battleView()});body().querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const z=b.dataset.d;if(battle.def.includes(z))battle.def=battle.def.filter(x=>x!==z);else if(battle.def.length<2)battle.def.push(z);else return arenaToast('Можно закрыть только 2 зоны');battleView()});body().querySelector('[data-hit]')?.addEventListener('click',turn);body().querySelector('[data-finish]')?.addEventListener('click',()=>finish(false,'Игрок завершил бой'));body().querySelector('[data-extend]')?.addEventListener('click',()=>{battle.endsAt+=300000;arenaToast('Бой продлён на 5 минут');battleView()});body().querySelector('[data-collapse]')?.addEventListener('click',x=>{const q=body().querySelector('.arena140-log-body');q.classList.toggle('collapsed');x.currentTarget.textContent=q.classList.contains('collapsed')?'Развернуть':'Свернуть'});
bt=setInterval(()=>{if(Date.now()>=battle.endsAt)finish(false,'Время боя истекло');else battleView()},1000)}
function turn(){if(!battle||!battle.attack||battle.def.length!==2)return;const s=st(),d=Math.max(8,Math.round((+(s.strength||5)+ +(s.bonusDamage||0)+10)*(0.9+Math.random()*.35)));battle.enemyHp=Math.max(0,battle.enemyHp-d);battle.log.push(`🎯 ${A.find(x=>x[0]===battle.attack)[1]}: -${d} HP`);if(battle.enemyHp<=0)return finish(true,'Противник повержен');const enemy=A[Math.floor(Math.random()*A.length)][0];if(!battle.def.includes(enemy)){const hit=Math.max(4,Math.round(9+Math.random()*10- +(s.defense||0)*.35));battle.playerHp=Math.max(0,battle.playerHp-hit);battle.log.push(`⚡ Ответный удар: -${hit} HP`)}else battle.log.push(`🛡️ Защита закрыла ${A.find(x=>x[0]===enemy)[1]}`);if(battle.playerHp<=0)return finish(false,'Ты проиграл бой');battle.round++;battle.attack=null;battle.def=[];battleView()}
function finish(win,reason){if(!battle)return;clearInterval(bt);stats.battles=(stats.battles||0)+1;if(win)stats.wins=(stats.wins||0)+1;else stats.losses=(stats.losses||0)+1;stats.history=(stats.history||[]);stats.history.push({win,mode:lobby?.mode||'Бой',result:win?'победа':'поражение'});if(stats.history.length>20)stats.history.shift();saveStats();const m=win?'🏆 Победа!':'⚔️ Бой завершён';show('⚔️ Результат',`<div class="arena140 arena140-result"><section class="arena140-end"><div class="big">${win?'🏆':'⚔️'}</div><h2>${m}</h2><p>${esc(reason)}</p><button class="arena140-primary" data-home>🏟️ В арену</button></section></div>`);body().querySelector('[data-home]')?.addEventListener('click',home)}
window.openBattle=home;window.openArena=home;

/* FIX: bind the actual close button used by index.html. */
document.addEventListener('click',e=>{if(e.target.closest('#arenaClose,[data-arena-close]'))close()});
const mm=modal();if(mm)mm.addEventListener('click',e=>{if(e.target===mm)close()});
})();
