(function(){'use strict';
const items=[['home','🏰','Город'],['inventory','🎒','Инвентарь'],['hero','🪖','Герой'],['battle','⚔️','Бой'],['quests','📜','Квесты'],['games','🎲','Игры'],['clan','🚩','Клан']];
const aliases={market:'shop',casino:'games',districts:'quests',profile:'hero'};
let original=null;
function combat(){return !!document.querySelector('#runnerScreen,.pve-battle.show,.arena-modal.arena-in-battle.show')}
function sync(){const bar=document.getElementById('territoryNav');if(!bar)return;const active=document.body.dataset.screen||'home';bar.classList.toggle('hidden',combat());bar.querySelectorAll('button[data-screen]').forEach(b=>b.classList.toggle('active',aliases[active]===b.dataset.screen||active===b.dataset.screen))}
function go(id,push=true){id=aliases[id]||id;if(id==='battle'){return window.HomeRebuild?.startRunner?.(false)};if(id==='home'){window.PvEFlow?.stop?.();window.ArenaGame?.close?.();document.querySelectorAll('.arena-modal').forEach(x=>x.classList.remove('show'));document.querySelectorAll('.pve-battle.show').forEach(x=>x.classList.remove('show'));document.querySelector('#runnerScreen')?.remove()}original?.(id);if(push)history.pushState({screen:id},'',`#${id}`);sync()}
function mount(){if(document.getElementById('territoryNav'))return;const bar=document.createElement('nav');bar.id='territoryNav';bar.className='global-nav';bar.innerHTML=items.map(x=>`<button data-screen="${x[0]}"><span>${x[1]}</span><b>${x[2]}</b></button>`).join('');document.body.appendChild(bar);bar.addEventListener('click',e=>{const b=e.target.closest('button[data-screen]');if(b)go(b.dataset.screen)});}
function init(){mount();original=window.showScreen;window.showScreen=function(id){go(id,true)};window.TerritoryUI&&(window.TerritoryUI.show=window.showScreen);window.addEventListener('territory:screen',sync);window.addEventListener('popstate',e=>{const id=e.state?.screen||location.hash.slice(1)||'home';if(id==='home'&&!combat())original?.('home');else if(!combat())original?.(aliases[id]||id);else if(id==='home')go('home',false);sync()});history.replaceState({screen:document.body.dataset.screen||'home'},'',location.href);sync()}
window.TerritoryNavigation={go,sync};document.addEventListener('DOMContentLoaded',init);})();
