/* Territory Game — reference-style inventory screen */
(function(){
'use strict';
const S=()=>window.TerritoryStore?.state||{};
const slots=[{key:'weapon',name:'Оружие',icon:'⚔',gem:'orange',base:8},{key:'belt',name:'Пояс',icon:'◉',gem:'silver',base:7},{key:'boots',name:'Сапоги',icon:'♞',gem:'purple',base:7},{key:'shoulders',name:'Наплечники',icon:'◆',gem:'orange',base:7},{key:'pants',name:'Военные штаны',icon:'▣',gem:'blue',base:7},{key:'helmet',name:'Шлем',icon:'⬟',gem:'green',base:6}];
function weaponName(){return String(S().weapon||'Кулаки');}
function levelFor(slot,i){const s=S(),eq=Array.isArray(s.equipment)?s.equipment:[],item=eq.find(x=>x?.slot===slot.key),raw=item?.level??(slot.key==='weapon'?(s.level||1):slot.base-i);return Math.max(1,Number(raw)||1);}
function render(){const screen=document.getElementById('inventory'),grid=document.getElementById('inventoryGrid');if(!screen||!grid)return;screen.classList.add('reference-inventory');grid.className='reference-wrap';grid.innerHTML='';const top=document.createElement('div');top.className='reference-topbar';top.innerHTML='<button class="reference-back" type="button" data-screen="home">‹</button><div class="reference-title">ИНВЕНТАРЬ<small>ЭКИПИРОВКА ГЕРОЯ</small></div>';const main=document.createElement('div');main.className='reference-main';const stage=document.createElement('div');stage.className='reference-stage';stage.innerHTML='<div class="reference-gem-slot"><span class="gem purple"></span></div><div class="reference-stage-label">ЦЕНТР ЭКИПИРОВКИ</div>';const stageGem=stage.querySelector('.gem');stageGem.style.width='42px';stageGem.style.height='42px';const divider=document.createElement('div');divider.className='reference-divider';const list=document.createElement('div');list.className='reference-equip-list';slots.forEach((slot,idx)=>{const row=document.createElement('div');row.className='reference-row'+(slot.key==='weapon'?' selected':'');const label=document.createElement('div');label.className='reference-row-label';label.innerHTML='<span class="slot-icon">'+slot.icon+'</span><span>'+slot.name+'</span>';row.appendChild(label);for(let i=0;i<3;i++){const b=document.createElement('button');b.type='button';b.className='reference-orb';const lvl=levelFor(slot,i),gemClass=slot.gem;b.innerHTML='<span class="gem '+gemClass+'"></span><span class="orb-level">Lv.'+lvl+'</span><span class="orb-bonus">+'+(i===0?9.6:7)+'%</span>';b.dataset.slot=slot.key;b.dataset.index=i;b.addEventListener('click',()=>selectRow(row,slot));row.appendChild(b);}list.appendChild(row);});main.appendChild(stage);main.appendChild(divider);main.appendChild(list);const bottom=document.createElement('div');bottom.className='reference-bottom';bottom.innerHTML='<button class="reference-bottom-back" type="button" data-screen="home">↩</button><span class="reference-bottom-status">Territory Game • '+weaponName()+'</span>';grid.appendChild(top);grid.appendChild(main);grid.appendChild(bottom);}
function selectRow(row,slot){document.querySelectorAll('.reference-row').forEach(x=>x.classList.remove('selected'));row.classList.add('selected');const title=document.querySelector('.reference-title');if(title)title.firstChild.textContent=slot.name+' ';}
document.addEventListener('territory:render',()=>{if(document.getElementById('inventory')?.classList.contains('active'))render();});document.addEventListener('DOMContentLoaded',()=>{render();const observer=new MutationObserver(()=>{if(document.getElementById('inventory')?.classList.contains('active')&&!document.querySelector('#inventory.reference-inventory .reference-wrap'))render();});const inv=document.getElementById('inventory');if(inv)observer.observe(inv,{attributes:true,attributeFilter:['class']});});
})();