(()=>{'use strict';
const tg=()=>window.Telegram&&Telegram.WebApp?Telegram.WebApp:null;
const pid=()=>{const u=tg()?.initDataUnsafe?.user;if(u?.id)return String(u.id);let id=localStorage.getItem('territory_player_id');if(!id){id='local-'+Math.random().toString(36).slice(2,10);localStorage.setItem('territory_player_id',id)}return id};
const pname=()=>{const u=tg()?.initDataUnsafe?.user;return [u?.first_name,u?.last_name].filter(Boolean).join(' ')||'Игрок'};
async function api(path,opt={}){const h={'content-type':'application/json'};const t=tg();if(t?.initData)h['X-Telegram-Init-Data']=t.initData;const r=await fetch(path,{...opt,headers:{...h,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка сервера');return d}
function ensure(){return api('/api/profile',{method:'POST',body:JSON.stringify({playerId:pid(),name:pname()})}).catch(()=>null)}
function cleanupLegacy(){document.querySelectorAll('.s72-btn,.s73-btn,.s74-btn').forEach(e=>e.remove());document.querySelectorAll('button').forEach(b=>{const t=(b.textContent||'').trim();if(t.includes('Командный штаб')||t.includes('ОСАДА')||t.includes('ЛОГИСТИКА'))b.remove()});document.querySelectorAll('[id^=\"s72-\"],[id^=\"s73-\"],[id^=\"s74-\"]').forEach(e=>e.remove())}
const css=`
#s102nav{position:fixed;left:7px;right:7px;bottom:7px;z-index:999990;display:grid;grid-template-columns:repeat(6,1fr);gap:5px;padding:6px;border:1px solid #5c4a2c;border-radius:15px;background:rgba(12,12,13,.94);backdrop-filter:blur(12px);box-shadow:0 8px 30px #0008}
#s102nav button{min-height:45px;border:1px solid #34302a;border-radius:10px;background:#191817;color:#ddd;font-size:10px;font-weight:800}#s102nav button:active{transform:scale(.97);background:#2b2418}#s102nav b{display:block;font-size:17px;margin-bottom:1px}
.s102shade{position:fixed;inset:0;z-index:999980;background:rgba(0,0,0,.72);backdrop-filter:blur(3px)}
.s102sheet{position:fixed;z-index:999981;left:3%;right:3%;top:5%;bottom:10%;overflow:auto;border:1px solid #634d2b;border-radius:18px;background:linear-gradient(180deg,#171615,#0d0d0d);color:#eee;box-shadow:0 20px 60px #000; padding:12px}
.s102head{display:flex;align-items:center;justify-content:space-between;position:sticky;top:-12px;padding:6px 0 12px;background:#151413;z-index:2}.s102head h2{font-size:18px;margin:0}.s102close{width:38px;height:38px;border-radius:10px;border:1px solid #493c2a;background:#211b14;color:#fff;font-size:22px}
.s102grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.s102card{padding:10px;border:1px solid #35312b;border-radius:12px;background:#191817}.s102card b{display:block}.s102muted{opacity:.65;font-size:11px}.s102btn{width:100%;padding:10px;border-radius:10px;border:1px solid #76572e;background:#241b10;color:#f1d39b;font-weight:800;margin-top:7px}.s102danger{border-color:#713b3b;background:#241313}.s102row{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #292724}.s102chips{display:flex;gap:6px;flex-wrap:wrap}.s102chip{padding:8px 9px;border-radius:9px;border:1px solid #39342d;background:#171615;color:#ddd}.s102chip.on{border-color:#b98a42;background:#2a2115;color:#f4d79d}.s102hp{height:8px;border-radius:9px;background:#282522;overflow:hidden}.s102hp i{display:block;height:100%;background:#9d513f}.s102battle{display:grid;grid-template-columns:1fr 1fr;gap:8px}.s102fighter{padding:10px;border:1px solid #39342d;border-radius:13px;background:#151515;text-align:center}.s102fighter .face{font-size:42px}.s102log{font-size:11px;opacity:.75;max-height:100px;overflow:auto;margin-top:7px}.s102note{padding:10px;border:1px solid #3c3326;border-radius:12px;background:#1b1712;margin:8px 0;font-size:12px}
@media(max-width:360px){#s102nav button{font-size:9px}.s102grid{grid-template-columns:repeat(2,1fr)}}
`;
function style(){if(document.getElementById('s102css'))return;const s=document.createElement('style');s.id='s102css';s.textContent=css;document.head.appendChild(s)}
function sheet(title,body){document.getElementById('s102root')?.remove();const r=document.createElement('div');r.id='s102root';r.innerHTML=`<div class="s102shade"></div><section class="s102sheet"><header class="s102head"><h2>${title}</h2><button class="s102close">×</button></header><div id="s102body">${body}</div></section>`;document.body.appendChild(r);r.querySelector('.s102close').onclick=()=>r.remove();r.querySelector('.s102shade').onclick=()=>r.remove();return r.querySelector('#s102body')}
function nav(){if(document.getElementById('s102nav'))return;const n=document.createElement('nav');n.id='s102nav';n.innerHTML=`<button data-a="char"><b>🧍</b>Персонаж</button><button data-a="bag"><b>🎒</b>Рюкзак</button><button data-a="market"><b>🏪</b>Рынок</button><button data-a="quests"><b>📜</b>Квесты</button><button data-a="city"><b>🗺️</b>Сдоларс</button><button data-a="arena"><b>⚔️</b>Арена</button>`;document.body.appendChild(n);n.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.a))}
async function character(){const b=sheet('🧍 Персонаж','Загрузка…');const d=await api('/api/character?id='+encodeURIComponent(pid()));const s=d.stats;b.innerHTML=`<div class="s102grid"><div class="s102card">Уровень<b>${s.level}</b><span class="s102muted">XP ${s.xp}/${s.nextXp}</span></div><div class="s102card">🪙 Монеты<b>${s.coins}</b></div><div class="s102card">⚔️ Атака<b>${s.attackPower}</b></div><div class="s102card">❤️ HP<b>${s.maxHp}</b></div><div class="s102card">💪 Сила<b>${s.strength}</b></div><div class="s102card">🏃 Ловкость<b>${s.agility}</b></div><div class="s102card">⚡ Крит<b>${Number(s.critChance).toFixed(1)}%</b></div><div class="s102card">💨 Уклонение<b>${Number(s.dodgeChance).toFixed(1)}%</b></div><div class="s102card">⭐ Очки<b>${s.freePoints}</b></div></div><div class="s102note">Оружие: ${s.equipment.weapon||'Кулаки'} · Броня: ${s.equipment.armor||'нет'} · Пояс: ${s.equipment.belt||'нет'}</div><button class="s102btn" id="s102str">+1 Сила</button><button class="s102btn" id="s102agi">+1 Ловкость</button><button class="s102btn s102danger" id="s102reset">Сбросить распределение</button>`;b.querySelector('#s102str').onclick=()=>up('strength');b.querySelector('#s102agi').onclick=()=>up('agility');b.querySelector('#s102reset').onclick=async()=>{await api('/api/character/reset-points',{method:'POST',body:JSON.stringify({playerId:pid()})});character()};async function up(stat){try{await api('/api/character/upgrade',{method:'POST',body:JSON.stringify({playerId:pid(),stat,count:1})});character()}catch(e){alert(e.message)}}}
async function backpack(){const b=sheet('🎒 Рюкзак','Загрузка…');const d=await api('/api/equipment?playerId='+encodeURIComponent(pid()));b.innerHTML=`<div class="s102note">🪙 ${d.coins} монет · ${d.items.length} видов</div><div class="s102grid">${d.items.map(x=>`<div class="s102card"><b>${icon(x.id)} ${x.name}</b><span class="s102muted">×${x.quantity} · ${x.type}</span><button class="s102btn" data-e="${x.id}">${equipped(d.equipment,x.id)?'Снять':'Экипировать'}</button>${x.id!=='fists'?`<button class="s102btn s102danger" data-d="${x.id}">Выбросить</button>`:''}</div>`).join('')}</div>`;b.querySelectorAll('[data-e]').forEach(x=>x.onclick=async()=>{const id=x.dataset.e;await api(equipped(d.equipment,id)?'/api/equipment/unequip':'/api/equipment/equip',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:id})});backpack()});b.querySelectorAll('[data-d]').forEach(x=>x.onclick=async()=>{if(confirm('Выбросить предмет?')){await api('/api/equipment/drop',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:x.dataset.d,quantity:1})});backpack()}})}
function equipped(e,id){return e.weapon===id||e.armor===id||e.belt===id}function icon(id){return ({iron_sword:'⚔️',viking_axe:'🪓',steel_armor:'🛡️',leather_belt:'🥋',fists:'✊'})[id]||'📦'}
async function market(){const b=sheet('🏪 Рынок Сдоларса','Загрузка…');const d=await api('/api/market?playerId='+encodeURIComponent(pid()));b.innerHTML=`<div class="s102note">🪙 ${d.coins} монет</div><div class="s102grid">${d.items.map(x=>`<div class="s102card"><b>${icon(x.id)} ${x.name}</b><span class="s102muted">${x.type}</span><div style="margin-top:7px">${x.price} 🪙</div><button class="s102btn" data-buy="${x.id}">Купить</button></div>`).join('')}</div>`;b.querySelectorAll('[data-buy]').forEach(x=>x.onclick=async()=>{try{await api('/api/market/buy',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:x.dataset.buy,quantity:1})});market()}catch(e){alert(e.message)}})}
async function quests(){const b=sheet('📜 Квесты','Загрузка…');const d=await api('/api/quests?id='+encodeURIComponent(pid()));b.innerHTML=d.quests.map(q=>`<div class="s102card" style="margin-bottom:7px"><b>${q.name}</b><span class="s102muted">${q.desc}</span><div class="s102row"><span>${q.progress}/${q.goal}</span><span>+${q.xp} XP · +${q.coins} 🪙</span></div>${q.completed&&!q.claimed?`<button class="s102btn" data-q="${q.id}">Забрать награду</button>`:q.claimed?'<div class="s102muted">Награда получена</div>':'<div class="s102muted">Продолжай играть</div>'}</div>`).join('');b.querySelectorAll('[data-q]').forEach(x=>x.onclick=async()=>{await api('/api/quests/claim',{method:'POST',body:JSON.stringify({playerId:pid(),questId:x.dataset.q})});quests()})}
async function city(){const b=sheet('🗺️ Сдоларс','Загрузка…');const d=await api('/api/districts?id='+encodeURIComponent(pid()));b.innerHTML=`<div class="s102note">Город Сдоларс · открывай районы по уровню и забирай награды.</div><div>${d.districts.map(x=>`<div class="s102card" style="margin-bottom:7px"><div class="s102row"><b>${x.name}</b><span>опасность ${x.danger}</span></div><span class="s102muted">Требуется уровень ${x.level} · награда ${x.reward} 🪙</span>${x.completed?'<div class="s102muted">Район пройден</div>':x.unlocked?`<button class="s102btn" data-dist="${x.id}">Исследовать</button>`:`<button class="s102btn" disabled>Закрыт</button>`}</div>`).join('')}</div>`;b.querySelectorAll('[data-dist]').forEach(x=>x.onclick=async()=>{try{await api('/api/districts/claim',{method:'POST',body:JSON.stringify({playerId:pid(),districtId:x.dataset.dist})});city()}catch(e){alert(e.message)}})}
let battle=null,attack='chest',defs=['head','legs'];
async function loadIncoming(){const d=await api('/api/pvp/incoming?id='+encodeURIComponent(pid())).catch(()=>({matches:[]}));return d.matches||[]}
async function arena(){const b=sheet('⚔️ Арена','Загрузка…');const p=await api('/api/players');const incoming=await loadIncoming();const list=p.players.filter(x=>x.id!==pid());b.innerHTML=`<div class="s102note">Тактический бой: выбери ровно 1 атаку и ровно 2 защиты.</div>${incoming.length?`<div class="s102card" style="margin-bottom:8px"><b>Входящие вызовы</b>${incoming.map(m=>`<div class="s102row"><span>${m.attacker.name}</span><button class="s102btn" data-accept="${m.id}">Принять</button></div>`).join('')}</div>`:''}<div class="s102grid">${list.map(x=>`<div class="s102card"><b>${x.name}</b><span class="s102muted">ур. ${x.level}</span><button class="s102btn" data-ch="${x.id}">Вызвать</button></div>`).join('')||'<div class="s102muted">Других бойцов пока нет.</div>'}</div>`;b.querySelectorAll('[data-accept]').forEach(x=>x.onclick=async()=>{try{const d=await api('/api/pvp/accept',{method:'POST',body:JSON.stringify({playerId:pid(),matchId:x.dataset.accept})});battle=d.match;attack='chest';defs=['head','legs'];fight()}catch(e){alert(e.message)}});b.querySelectorAll('[data-ch]').forEach(x=>x.onclick=async()=>{try{await api('/api/pvp/challenge',{method:'POST',body:JSON.stringify({playerId:pid(),targetId:x.dataset.ch})});alert('Вызов отправлен. Ожидаем принятия соперником.')}catch(e){alert(e.message)}})}
function fight(){const b=sheet('⚔️ Тактический бой','');renderFight(b)}
function renderFight(b){if(!battle)return;const me=String(pid())===String(battle.attacker.id);const myHp=me?battle.attackerHp:battle.defenderHp,enemyHp=me?battle.defenderHp:battle.attackerHp;b.innerHTML=`<div class="s102battle"><div class="s102fighter"><div class="face">🛡️</div><b>${me?battle.attacker.name:battle.defender.name}</b><div>${myHp} HP</div></div><div class="s102fighter"><div class="face">⚔️</div><b>${me?battle.defender.name:battle.attacker.name}</b><div>${enemyHp} HP</div></div></div><div class="s102note">${String(battle.turn)===String(pid())?'ВАШ ХОД':'ХОД СОПЕРНИКА'}</div><b>Атака — 1 зона</b><div class="s102chips">${['head','chest','belt','legs'].map(z=>`<button class="s102chip ${attack===z?'on':''}" data-a="${z}">${zn(z)}</button>`).join('')}</div><b style="display:block;margin-top:10px">Защита — ровно 2 зоны</b><div class="s102chips">${['head','chest','belt','legs'].map(z=>`<button class="s102chip ${defs.includes(z)?'on':''}" data-d="${z}">${zn(z)}</button>`).join('')}</div><button class="s102btn" id="s102hit" ${String(battle.turn)!==String(pid())?'disabled':''}>Нанести удар</button><div class="s102log">${(battle.log||[]).slice(-8).map(x=>'<div>'+escapeHtml(x.text||'')+'</div>').join('')}</div>`;b.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>{attack=x.dataset.a;renderFight(b)});b.querySelectorAll('[data-d]').forEach(x=>x.onclick=()=>{const z=x.dataset.d;if(defs.includes(z)){defs=defs.filter(v=>v!==z)}else if(defs.length<2&&z!==attack)defs=[...defs,z];renderFight(b)});b.querySelector('#s102hit').onclick=async()=>{try{const d=await api('/api/pvp/action',{method:'POST',body:JSON.stringify({playerId:pid(),matchId:battle.id,zone:attack,defenseZones:defs})});battle=d.match;renderFight(b)}catch(e){alert(e.message)}}}
function zn(z){return ({head:'Голова',chest:'Грудь',belt:'Пояс',legs:'Ноги'})[z]}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function open(a){try{if(a==='char')return character();if(a==='bag')return backpack();if(a==='market')return market();if(a==='quests')return quests();if(a==='city')return city();if(a==='arena')return arena()}catch(e){alert(e.message)}}
function boot(){style();cleanupLegacy();nav();ensure();window.TerritoryS102={open,playerId:pid}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
