(()=>{'use strict';
const tg=()=>window.Telegram&&Telegram.WebApp?Telegram.WebApp:null;
const pid=()=>{const u=tg()?.initDataUnsafe?.user;if(u?.id)return String(u.id);let id=localStorage.getItem('territory_player_id');if(!id){id='local-'+Math.random().toString(36).slice(2,10);localStorage.setItem('territory_player_id',id)}return id};
const pname=()=>{const u=tg()?.initDataUnsafe?.user;return [u?.first_name,u?.last_name].filter(Boolean).join(' ')||'Игрок'};
async function api(path,opt={}){const h={'content-type':'application/json'};const t=tg();if(t?.initData)h['X-Telegram-Init-Data']=t.initData;const r=await fetch(path,{...opt,headers:{...h,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка сервера');return d}
function ensure(){return api('/api/profile',{method:'POST',body:JSON.stringify({playerId:pid(),name:pname()})}).catch(()=>null)}
function cleanupLegacy(){document.querySelectorAll('.s72-btn,.s73-btn,.s74-btn').forEach(e=>e.remove());document.querySelectorAll('button').forEach(b=>{const t=(b.textContent||'').trim();if(t.includes('Командный штаб')||t.includes('ОСАДА')||t.includes('ЛОГИСТИКА'))b.remove()});document.querySelectorAll('[id^=\"s72-\"],[id^=\"s73-\"],[id^=\"s74-\"]').forEach(e=>e.remove())}
const css=`
#s102nav{position:fixed;left:7px;right:7px;bottom:7px;z-index:999990;display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px;padding:6px;border:1px solid #5c4a2c;border-radius:15px;background:rgba(12,12,13,.94);backdrop-filter:blur(12px);box-shadow:0 8px 30px #0008}
#s102nav button{min-height:45px;min-width:0;padding:3px 1px;border:1px solid #34302a;border-radius:10px;background:#191817;color:#ddd;font-size:8px;font-weight:800;white-space:normal;line-height:1.05}#s102nav button:active{transform:scale(.97);background:#2b2418}#s102nav b{display:block;font-size:15px;margin-bottom:1px}
.s102shade{position:fixed;inset:0;z-index:999980;background:rgba(0,0,0,.72);backdrop-filter:blur(3px)}
.s102sheet{position:fixed;z-index:999981;left:3%;right:3%;top:5%;bottom:10%;overflow:auto;border:1px solid #634d2b;border-radius:18px;background:linear-gradient(180deg,#171615,#0d0d0d);color:#eee;box-shadow:0 20px 60px #000; padding:12px}
.s102head{display:flex;align-items:center;justify-content:space-between;position:sticky;top:-12px;padding:6px 0 12px;background:#151413;z-index:2}.s102head h2{font-size:18px;margin:0}.s102close{width:38px;height:38px;border-radius:10px;border:1px solid #493c2a;background:#211b14;color:#fff;font-size:22px}
.s102grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.s102card{padding:10px;border:1px solid #35312b;border-radius:12px;background:#191817}.s102card b{display:block}.s102muted{opacity:.65;font-size:11px}.s102btn{width:100%;padding:10px;border-radius:10px;border:1px solid #76572e;background:#241b10;color:#f1d39b;font-weight:800;margin-top:7px}.s102danger{border-color:#713b3b;background:#241313}.s102row{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #292724}.s102chips{display:flex;gap:6px;flex-wrap:wrap}.s102chip{padding:8px 9px;border-radius:9px;border:1px solid #39342d;background:#171615;color:#ddd}.s102chip.on{border-color:#b98a42;background:#2a2115;color:#f4d79d}.s102hp{height:8px;border-radius:9px;background:#282522;overflow:hidden}.s102hp i{display:block;height:100%;background:#9d513f}.s102battle{display:grid;grid-template-columns:1fr 1fr;gap:8px}.s102fighter{padding:10px;border:1px solid #39342d;border-radius:13px;background:#151515;text-align:center}.s102fighter .face{font-size:42px}.s102log{font-size:11px;opacity:.75;max-height:100px;overflow:auto;margin-top:7px}.s102note{padding:10px;border:1px solid #3c3326;border-radius:12px;background:#1b1712;margin:8px 0;font-size:12px}
@media(max-width:360px){#s102nav button{font-size:9px}.s102grid{grid-template-columns:repeat(2,1fr)}}
`;
function style(){if(document.getElementById('s102css'))return;const s=document.createElement('style');s.id='s102css';s.textContent=css;document.head.appendChild(s)}
function sheet(title,body){document.getElementById('s102root')?.remove();const r=document.createElement('div');r.id='s102root';r.innerHTML=`<div class="s102shade"></div><section class="s102sheet"><header class="s102head"><h2>${title}</h2><button class="s102close">×</button></header><div id="s102body">${body}</div></section>`;document.body.appendChild(r);r.querySelector('.s102close').onclick=()=>r.remove();r.querySelector('.s102shade').onclick=()=>r.remove();return r.querySelector('#s102body')}
function nav(){if(document.getElementById('s102nav'))return;const n=document.createElement('nav');n.id='s102nav';n.innerHTML=`<button data-a="char"><b>🧍</b>Персонаж</button><button data-a="bag"><b>🎒</b>Рюкзак</button><button data-a="market"><b>🏪</b>Рынок</button><button data-a="quests"><b>📜</b>Квесты</button><button data-a="city"><b>🗺️</b>Сдоларс</button><button data-a="arena"><b>⚔️</b>Арена</button>`;document.body.appendChild(n);n.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.a))}
async function character(){const b=sheet('🧍 Персонаж','Загрузка…');const d=await api('/api/character?id='+encodeURIComponent(pid()));const s=d.stats;b.innerHTML=`<div class="s102grid"><div class="s102card">Уровень<b>${s.level}</b><span class="s102muted">XP ${s.xp}/${s.nextXp}</span></div><div class="s102card">🪙 Монеты<b>${s.coins}</b></div><div class="s102card">⚔️ Атака<b>${s.attackPower}</b></div><div class="s102card">❤️ HP<b>${s.maxHp}</b></div><div class="s102card">💪 Сила<b>${s.strength}</b></div><div class="s102card">🏃 Ловкость<b>${s.agility}</b></div><div class="s102card">⚡ Крит<b>${Number(s.critChance).toFixed(1)}%</b></div><div class="s102card">💨 Уклонение<b>${Number(s.dodgeChance).toFixed(1)}%</b></div><div class="s102card">⭐ Очки<b>${s.freePoints}</b></div></div><div class="s102note">Оружие: ${s.equipment.weapon||'Кулаки'} · Броня: ${s.equipment.armor||'нет'} · Пояс: ${s.equipment.belt||'нет'}</div><button class="s102btn" id="s102str">+1 Сила</button><button class="s102btn" id="s102agi">+1 Ловкость</button><button class="s102btn s102danger" id="s102reset">Сбросить распределение</button>`;b.querySelector('#s102str').onclick=()=>up('strength');b.querySelector('#s102agi').onclick=()=>up('agility');b.querySelector('#s102reset').onclick=async()=>{await api('/api/character/reset-points',{method:'POST',body:JSON.stringify({playerId:pid()})});character()};async function up(stat){try{await api('/api/character/upgrade',{method:'POST',body:JSON.stringify({playerId:pid(),stat,count:1})});character()}catch(e){alert(e.message)}}}
async function backpack(){const b=sheet('🎒 Рюкзак','Загрузка…');const d=await api('/api/equipment?playerId='+encodeURIComponent(pid()));b.innerHTML=`<div class="s102note">🪙 ${d.coins} монет · ${d.items.length} видов</div><div class="s102grid">${d.items.map(x=>`<div class="s102card"><b>${icon(x.id)} ${x.name}</b><span class="s102muted">×${x.quantity} · ${x.type}</span><button class="s102btn" data-e="${x.id}">${equipped(d.equipment,x.id)?'Снять':'Экипировать'}</button>${x.id!=='fists'?`<button class="s102btn s102danger" data-d="${x.id}">Выбросить</button>`:''}</div>`).join('')}</div>`;b.querySelectorAll('[data-e]').forEach(x=>x.onclick=async()=>{const id=x.dataset.e;await api(equipped(d.equipment,id)?'/api/equipment/unequip':'/api/equipment/equip',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:id})});backpack()});b.querySelectorAll('[data-d]').forEach(x=>x.onclick=async()=>{if(confirm('Выбросить предмет?')){await api('/api/equipment/drop',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:x.dataset.d,quantity:1})});backpack()}})}
function equipped(e,id){return e.weapon===id||e.armor===id||e.belt===id}function icon(id){return ({iron_sword:'⚔️',viking_axe:'🪓',steel_armor:'🛡️',leather_belt:'🥋',fists:'✊'})[id]||'📦'}
async function market(){const b=sheet('🏪 Рынок Сдоларса','Загрузка…');const d=await api('/api/market?playerId='+encodeURIComponent(pid()));b.innerHTML=`<div class="s102note">🪙 ${d.coins} монет · Покупка и продажа снаряжения</div><div class="s102grid">${d.items.map(x=>`<div class="s102card"><b>${icon(x.id)} ${x.name}</b><span class="s102muted">${x.type}</span><div style="margin-top:7px">${x.price} 🪙 · продажа ${Math.floor(x.price/2)} 🪙</div><button class="s102btn" data-buy="${x.id}">Купить</button><button class="s102btn s102danger" data-sell="${x.id}">Продать</button></div>`).join('')}</div>`;b.querySelectorAll('[data-buy]').forEach(x=>x.onclick=async()=>{try{await api('/api/market/buy',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:x.dataset.buy,quantity:1})});market()}catch(e){alert(e.message)}});b.querySelectorAll('[data-sell]').forEach(x=>x.onclick=async()=>{try{await api('/api/market/sell',{method:'POST',body:JSON.stringify({playerId:pid(),itemId:x.dataset.sell,quantity:1})});market()}catch(e){alert(e.message)}})}
async function quests(){const b=sheet('📜 Квесты','Загрузка…');const d=await api('/api/quests?id='+encodeURIComponent(pid()));b.innerHTML=d.quests.map(q=>`<div class="s102card" style="margin-bottom:7px"><b>${q.name}</b><span class="s102muted">${q.desc}</span><div class="s102row"><span>${q.progress}/${q.goal}</span><span>+${q.xp} XP · +${q.coins} 🪙</span></div>${q.completed&&!q.claimed?`<button class="s102btn" data-q="${q.id}">Забрать награду</button>`:q.claimed?'<div class="s102muted">Награда получена</div>':'<div class="s102muted">Продолжай играть</div>'}</div>`).join('');b.querySelectorAll('[data-q]').forEach(x=>x.onclick=async()=>{await api('/api/quests/claim',{method:'POST',body:JSON.stringify({playerId:pid(),questId:x.dataset.q})});quests()})}
async function city(){const b=sheet('🗺️ Сдоларс','Загрузка…');const d=await api('/api/districts?id='+encodeURIComponent(pid()));b.innerHTML=`<div class="s102note">Город Сдоларс · открывай районы по уровню и забирай награды.</div><div>${d.districts.map(x=>`<div class="s102card" style="margin-bottom:7px"><div class="s102row"><b>${x.name}</b><span>опасность ${x.danger}</span></div><span class="s102muted">Требуется уровень ${x.level} · награда ${x.reward} 🪙</span>${x.completed?'<div class="s102muted">Район пройден</div>':x.unlocked?`<button class="s102btn" data-dist="${x.id}">Исследовать</button>`:`<button class="s102btn" disabled>Закрыт</button>`}</div>`).join('')}</div>`;b.querySelectorAll('[data-dist]').forEach(x=>x.onclick=async()=>{try{await api('/api/districts/claim',{method:'POST',body:JSON.stringify({playerId:pid(),districtId:x.dataset.dist})});city()}catch(e){alert(e.message)}})}
let battle=null,attack='chest',defs=['head','legs'];
async function loadIncoming(){const d=await api('/api/pvp/incoming?id='+encodeURIComponent(pid())).catch(()=>({matches:[]}));return d.matches||[]}
async function arena(){const b=sheet('⚔️ Арена','Загрузка…');const p=await api('/api/players');const incoming=await loadIncoming();const list=p.players.filter(x=>x.id!==pid());b.innerHTML=`<div class="s102note">Тактический бой: выбери ровно 1 атаку и ровно 2 защиты.</div>${incoming.length?`<div class="s102card" style="margin-bottom:8px"><b>Входящие вызовы</b>${incoming.map(m=>`<div class="s102row"><span>${m.attacker.name}</span><button class="s102btn" data-accept="${m.id}">Принять</button></div>`).join('')}</div>`:''}<div class="s102grid">${list.map(x=>`<div class="s102card"><b>${x.name}</b><span class="s102muted">ур. ${x.level}</span><button class="s102btn" data-ch="${x.id}">Вызвать</button></div>`).join('')||'<div class="s102muted">Других бойцов пока нет.</div>'}</div>`;b.querySelectorAll('[data-accept]').forEach(x=>x.onclick=async()=>{try{const d=await api('/api/pvp/accept',{method:'POST',body:JSON.stringify({playerId:pid(),matchId:x.dataset.accept})});battle=d.match;attack='chest';defs=['head','legs'];fight()}catch(e){alert(e.message)}});b.querySelectorAll('[data-ch]').forEach(x=>x.onclick=async()=>{try{await api('/api/pvp/challenge',{method:'POST',body:JSON.stringify({playerId:pid(),targetId:x.dataset.ch})});alert('Вызов отправлен. Ожидаем принятия соперником.')}catch(e){alert(e.message)}})}
function fight(){const b=sheet('⚔️ Тактический бой','');renderFight(b)}
function renderFight(b){if(!battle)return;const me=String(pid())===String(battle.attacker.id);const myHp=me?battle.attackerHp:battle.defenderHp,enemyHp=me?battle.defenderHp:battle.attackerHp;b.innerHTML=`<div class="s102battle"><div class="s102fighter"><div class="face">🛡️</div><b>${me?battle.attacker.name:battle.defender.name}</b><div>${myHp} HP</div></div><div class="s102fighter"><div class="face">⚔️</div><b>${me?battle.defender.name:battle.attacker.name}</b><div>${enemyHp} HP</div></div></div><div class="s102note">${String(battle.turn)===String(pid())?'ВАШ ХОД':'ХОД СОПЕРНИКА'}</div><b>Атака — 1 зона</b><div class="s102chips">${['head','chest','belt','legs'].map(z=>`<button class="s102chip ${attack===z?'on':''}" data-a="${z}">${zn(z)}</button>`).join('')}</div><b style="display:block;margin-top:10px">Защита — ровно 2 зоны</b><div class="s102chips">${['head','chest','belt','legs'].map(z=>`<button class="s102chip ${defs.includes(z)?'on':''}" data-d="${z}">${zn(z)}</button>`).join('')}</div><button class="s102btn" id="s102hit" ${String(battle.turn)!==String(pid())?'disabled':''}>Нанести удар</button><div class="s102log">${(battle.log||[]).slice(-8).map(x=>'<div>'+escapeHtml(x.text||'')+'</div>').join('')}</div>`;b.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>{attack=x.dataset.a;renderFight(b)});b.querySelectorAll('[data-d]').forEach(x=>x.onclick=()=>{const z=x.dataset.d;if(defs.includes(z)){defs=defs.filter(v=>v!==z)}else if(defs.length<2&&z!==attack)defs=[...defs,z];renderFight(b)});b.querySelector('#s102hit').onclick=async()=>{try{const d=await api('/api/pvp/action',{method:'POST',body:JSON.stringify({playerId:pid(),matchId:battle.id,zone:attack,defenseZones:defs})});battle=d.match;renderFight(b)}catch(e){alert(e.message)}}}
function zn(z){return ({head:'Голова',chest:'Грудь',belt:'Пояс',legs:'Ноги'})[z]}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function open(a){try{if(a==='char')return character();if(a==='bag')return backpack();if(a==='market')return market();if(a==='quests')return quests();if(a==='city')return city();if(a==='arena')return arena();if(a==='people')return people()}catch(e){alert(e.message)}}
function boot(){style();cleanupLegacy();nav();ensure();window.TerritoryS102={open,playerId:pid}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
(()=>{'use strict';
const tg=()=>window.Telegram&&Telegram.WebApp?Telegram.WebApp:null;
const pid=()=>{const u=tg()?.initDataUnsafe?.user;if(u?.id)return String(u.id);return localStorage.getItem('territory_player_id')||''};
const pname=()=>{const u=tg()?.initDataUnsafe?.user;return [u?.first_name,u?.last_name].filter(Boolean).join(' ')||'Игрок'};
async function api(path,opt={}){const h={'content-type':'application/json'};const t=tg();if(t?.initData)h['X-Telegram-Init-Data']=t.initData;const r=await fetch(path,{...opt,headers:{...h,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка сервера');return d}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sheet(title,body){document.getElementById('s103guildroot')?.remove();const r=document.createElement('div');r.id='s103guildroot';r.innerHTML=`<div class="g103shade"></div><section class="g103sheet"><header><h2>${title}</h2><button class="g103close">×</button></header><div id="g103body">${body}</div></section>`;document.body.appendChild(r);r.querySelector('.g103close').onclick=()=>r.remove();r.querySelector('.g103shade').onclick=()=>r.remove();return r.querySelector('#g103body')}
const css=`#s102nav{grid-template-columns:repeat(4,minmax(0,1fr))!important;grid-auto-rows:48px!important;gap:5px!important;overflow:hidden!important}#s102nav button{min-width:0!important;width:auto!important}.g103shade{position:fixed;inset:0;z-index:1000000;background:rgba(0,0,0,.76);backdrop-filter:blur(4px)}.g103sheet{position:fixed;z-index:1000001;left:3%;right:3%;top:4%;bottom:9%;overflow:auto;border:1px solid #765b32;border-radius:18px;background:linear-gradient(180deg,#191817,#0b0b0b);color:#eee;box-shadow:0 22px 70px #000;padding:12px}.g103sheet header{position:sticky;top:-12px;z-index:3;display:flex;align-items:center;justify-content:space-between;padding:5px 0 12px;background:#171615}.g103sheet h2{margin:0;font:700 19px Georgia,serif}.g103close{width:38px;height:38px;border:1px solid #493c2a;border-radius:10px;background:#211b14;color:#fff;font-size:22px}.g103card{padding:11px;margin-bottom:8px;border:1px solid #37322b;border-radius:13px;background:#171615}.g103muted{display:block;color:#969087;font-size:11px;margin-top:3px}.g103row{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid #292724}.g103btn{width:100%;padding:10px;margin-top:7px;border:1px solid #76572e;border-radius:10px;background:#241b10;color:#f1d39b;font-weight:800}.g103danger{border-color:#713b3b;background:#241313}.g103input{width:100%;padding:11px;margin-top:7px;border:1px solid #40382e;border-radius:10px;background:#101010;color:#eee;outline:none}.g103grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.g103stat{padding:9px;border:1px solid #35312b;border-radius:11px;background:#1b1917}.g103tag{color:#d2ad6b;font-weight:800}.g103member{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid #292724}.g103mini{width:auto;padding:7px 9px;margin:0;font-size:11px}.g103invite{border:1px solid #51432e;border-radius:10px;padding:9px;background:#1a1712;margin:7px 0}`;
if(!document.getElementById('g103css')){const s=document.createElement('style');s.id='g103css';s.textContent=css;document.head.appendChild(s)}
async function profile(){return api('/api/profile?id='+encodeURIComponent(pid()))}
async function openGuild(){
 const b=sheet('⚜️ Гильдия','Загрузка…');
 try{
  const pr=await profile(), clanId=pr.profile?.clan;
  const inv=(await api('/api/clan/invites?id='+encodeURIComponent(pid())).catch(()=>({invites:[]}))).invites||[];
  if(clanId){
   const d=await api('/api/clan?id='+encodeURIComponent(clanId));
   const c=d.clan, leader=String(c.ownerId)===String(pid());
   b.innerHTML=`<div class="g103card"><div class="g103tag">[${esc(c.tag)}]</div><h3 style="margin:4px 0">${esc(c.name)}</h3><span class="g103muted">Уровень гильдии ${c.level} · XP ${c.xp} · Репутация ${c.reputation}</span><span class="g103muted">Казна: ${c.treasury} 🪙 · Участников: ${c.members.length}</span></div>
   <div class="g103grid"><div class="g103stat">⚔️ Сила состава<b>${c.members.reduce((n,m)=>n+Number(m.power||0),0)}</b></div><div class="g103stat">🏆 Лидер<b>${esc((c.members.find(m=>String(m.id)===String(c.ownerId))||{}).name||'—')}</b></div></div>
   <div class="g103card"><b>Участники</b>${c.members.map(m=>`<div class="g103member"><span>🧍 ${esc(m.name)}<span class="g103muted">ур. ${m.level} · ${m.role} · сила ${m.power}</span></span>${leader&&String(m.id)!==String(pid())?`<select class="g103role" data-member="${esc(m.id)}"><option value="warrior" ${m.role==='warrior'?'selected':''}>Боец</option><option value="officer" ${m.role==='officer'?'selected':''}>Офицер</option><option value="scout" ${m.role==='scout'?'selected':''}>Разведчик</option></select>`:''}</div>`).join('')}</div>
   ${leader?`<div class="g103card"><b>Пригласить игрока</b><input class="g103input" id="g103search" placeholder="Имя игрока"><button class="g103btn" id="g103find">Найти</button><div id="g103results"></div></div>`:''}
   <button class="g103btn g103danger" id="g103leave">${leader?'Роспуск пока недоступен — передай лидерство позже':'Покинуть гильдию'}</button>`;
   b.querySelectorAll('.g103role').forEach(x=>x.onchange=async()=>{try{await api('/api/clan/role',{method:'POST',body:JSON.stringify({playerId:pid(),memberId:x.dataset.member,role:x.value})});openGuild()}catch(e){alert(e.message)}});
   b.querySelector('#g103leave').onclick=async()=>{if(leader){alert('Лидер не может выйти из гильдии в текущей версии.')}else if(confirm('Покинуть гильдию?')){try{await api('/api/clan/leave',{method:'POST',body:JSON.stringify({playerId:pid()})});openGuild()}catch(e){alert(e.message)}}};
   const find=b.querySelector('#g103find');if(find)find.onclick=async()=>{const q=b.querySelector('#g103search').value.trim();const r=b.querySelector('#g103results');if(!q)return;r.innerHTML='Поиск…';const d=await api('/api/players?q='+encodeURIComponent(q));const arr=d.players.filter(x=>String(x.id)!==String(pid())&&!x.clan);r.innerHTML=arr.map(x=>`<div class="g103invite"><b>${esc(x.name)}</b><span class="g103muted">ур. ${x.level}</span><button class="g103btn g103mini" data-invite="${esc(x.id)}">Пригласить</button></div>`).join('')||'<span class="g103muted">Игрок не найден.</span>';r.querySelectorAll('[data-invite]').forEach(x=>x.onclick=async()=>{try{await api('/api/clan/invite',{method:'POST',body:JSON.stringify({playerId:pid(),targetId:x.dataset.invite})});x.textContent='Приглашение отправлено';x.disabled=true}catch(e){alert(e.message)}})};
   if(inv.length)b.insertAdjacentHTML('afterbegin',`<div class="g103card"><b>Новые приглашения</b>${inv.map(i=>`<div class="g103row"><span>Приглашение в гильдию</span><button class="g103btn g103mini" data-acc="${esc(i.id)}">Принять</button></div>`).join('')}</div>`);
   b.querySelectorAll('[data-acc]').forEach(x=>x.onclick=async()=>{try{await api('/api/clan/invite/accept',{method:'POST',body:JSON.stringify({playerId:pid(),inviteId:x.dataset.acc})});openGuild()}catch(e){alert(e.message)}});
  }else{
   b.innerHTML=`<div class="g103card"><b>Ты пока без гильдии</b><span class="g103muted">Создай свою или вступи в существующую. Гильдия станет основой командной игры Territory.</span></div>
   ${inv.length?`<div class="g103card"><b>Приглашения</b>${inv.map(i=>`<div class="g103row"><span>Приглашение в гильдию</span><button class="g103btn g103mini" data-acc="${esc(i.id)}">Принять</button></div>`).join('')}</div>`:''}
   <div class="g103card"><b>Создать гильдию</b><input class="g103input" id="gname" maxlength="32" placeholder="Название гильдии"><input class="g103input" id="gtag" maxlength="8" placeholder="Тег, например SDO"><button class="g103btn" id="gcreate">Создать</button></div>
   <div class="g103card"><b>Гильдии Сдоларса</b><input class="g103input" id="gq" placeholder="Поиск по названию или тегу"><button class="g103btn" id="gsearch">Показать</button><div id="glist"></div></div>`;
   b.querySelector('#gcreate').onclick=async()=>{try{await api('/api/clan/create',{method:'POST',body:JSON.stringify({playerId:pid(),playerName:pname(),name:b.querySelector('#gname').value,tag:b.querySelector('#gtag').value})});openGuild()}catch(e){alert(e.message)}};
   b.querySelector('#gsearch').onclick=async()=>{const q=b.querySelector('#gq').value.trim();const r=b.querySelector('#glist');r.innerHTML='Загрузка…';try{const d=await api('/api/clans?q='+encodeURIComponent(q));r.innerHTML=d.clans.map(c=>`<div class="g103card"><b>${esc(c.name)} <span class="g103tag">[${esc(c.tag)}]</span></b><span class="g103muted">ур. ${c.level} · ${c.members.length} участников</span><button class="g103btn" data-join="${esc(c.id)}">Вступить</button></div>`).join('')||'<span class="g103muted">Гильдий пока нет.</span>';r.querySelectorAll('[data-join]').forEach(x=>x.onclick=async()=>{try{await api('/api/clan/join',{method:'POST',body:JSON.stringify({playerId:pid(),playerName:pname(),clanId:x.dataset.join})});openGuild()}catch(e){alert(e.message)}})}catch(e){r.textContent=e.message}};
   b.querySelectorAll('[data-acc]').forEach(x=>x.onclick=async()=>{try{await api('/api/clan/invite/accept',{method:'POST',body:JSON.stringify({playerId:pid(),inviteId:x.dataset.acc})});openGuild()}catch(e){alert(e.message)}});
  }
 }catch(e){b.innerHTML=`<div class="g103card">Не удалось загрузить гильдию.<span class="g103muted">${esc(e.message)}</span></div>`}
}
async function people(){const b=sheet('👥 Люди Сдоларса','Загрузка…');const d=await api('/api/players');const list=(d.players||[]).filter(x=>String(x.id)!==String(pid()));b.innerHTML=`<div class="g103card"><b>Игроки Сдоларса</b><span class="g103muted">Здесь находятся бойцы, которых можно добавить в друзья или вызвать на арену.</span></div><div class="g103grid">${list.map(x=>`<div class="g103card"><b>🧍 ${esc(x.name)}</b><span class="g103muted">Уровень ${x.level}${x.clan?' · ⚜️ в гильдии':''}</span><button class="g103btn" data-friend="${esc(x.id)}">Добавить в друзья</button><button class="g103btn" data-challenge="${esc(x.id)}">⚔️ Вызвать</button></div>`).join('')||'<span class="g103muted">Других игроков пока нет.</span>'}</div>`;b.querySelectorAll('[data-friend]').forEach(x=>x.onclick=async()=>{try{await api('/api/friends',{method:'POST',body:JSON.stringify({playerId:pid(),targetId:x.dataset.friend})});x.textContent='Заявка отправлена';x.disabled=true}catch(e){alert(e.message)}});b.querySelectorAll('[data-challenge]').forEach(x=>x.onclick=async()=>{try{await api('/api/pvp/challenge',{method:'POST',body:JSON.stringify({playerId:pid(),targetId:x.dataset.challenge})});alert('Вызов отправлен.')}catch(e){alert(e.message)}})}
function addNav(){const n=document.getElementById('s102nav');if(!n)return;if(!n.querySelector('[data-a="guild"]')){const x=document.createElement('button');x.dataset.a='guild';x.innerHTML='<b>⚜️</b>Гильд.';x.onclick=openGuild;n.appendChild(x)}if(!n.querySelector('[data-a="people"]')){const x=document.createElement('button');x.dataset.a='people';x.innerHTML='<b>👥</b>Люди';x.onclick=people;n.appendChild(x)}}
function boot(){addNav();setTimeout(addNav,300);setTimeout(addNav,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
/* Territory S106 — живой игровой мир Sdolars поверх существующей игры */
(()=>{'use strict';
const WORLD_CSS=`
#s106-world{position:fixed;inset:0;z-index:1000;background:#080909;color:#eee;overflow:hidden;font-family:Arial,sans-serif;touch-action:none}
#s106-canvas{position:absolute;inset:0;width:100%;height:100%;display:block}
.s106-hud{position:absolute;top:10px;left:10px;right:10px;display:flex;align-items:center;gap:8px;pointer-events:none;z-index:3}
.s106-brand{padding:7px 11px;border:1px solid #6e542e;border-radius:12px;background:rgba(12,12,12,.86);box-shadow:0 5px 18px #0009;font-family:Georgia,serif;font-weight:700;letter-spacing:1px}
.s106-stats{flex:1;display:flex;gap:6px;justify-content:flex-end}.s106-pill{padding:7px 9px;border:1px solid #403a31;border-radius:11px;background:rgba(15,15,15,.86);font-size:11px;font-weight:700}.s106-hp{color:#e6a08c}.s106-coin{color:#e0bc72}
.s106-district{position:absolute;top:62px;left:50%;transform:translateX(-50%);padding:6px 12px;border:1px solid #6b512c;border-radius:999px;background:rgba(12,12,12,.72);font:700 11px Georgia,serif;letter-spacing:2px;z-index:3;white-space:nowrap}
.s106-actions{position:absolute;right:10px;bottom:108px;display:flex;flex-direction:column;gap:7px;z-index:4}.s106-action{width:46px;height:46px;border:1px solid #594629;border-radius:50%;background:rgba(18,17,15,.9);color:#e7d4ae;font-size:19px;box-shadow:0 5px 16px #0008}.s106-action:active{transform:scale(.94)}
.s106-joy{position:absolute;left:15px;bottom:104px;width:104px;height:104px;border:1px solid #594629;border-radius:50%;background:rgba(18,17,15,.42);z-index:4}.s106-stick{position:absolute;left:31px;top:31px;width:42px;height:42px;border-radius:50%;background:#695332;border:1px solid #9b7740;box-shadow:0 4px 14px #0008;transform:translate(0,0)}
.s106-hint{position:absolute;left:50%;bottom:84px;transform:translateX(-50%);padding:7px 12px;border:1px solid #413a31;border-radius:999px;background:rgba(8,8,8,.7);font-size:10px;color:#bdb5a8;z-index:3;opacity:0;transition:.25s;pointer-events:none}.s106-hint.show{opacity:1}
.s106-card{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:min(88%,360px);padding:16px;border:1px solid #73572f;border-radius:17px;background:rgba(16,15,14,.96);box-shadow:0 20px 60px #000;z-index:10}.s106-card h3{margin:0 0 6px;font:700 20px Georgia,serif}.s106-card p{margin:5px 0;color:#aaa;font-size:12px;line-height:1.45}.s106-card button{width:100%;margin-top:9px;padding:11px;border:1px solid #76572e;border-radius:11px;background:#241b10;color:#f1d39b;font-weight:800}.s106-close{position:absolute!important;right:9px;top:9px;width:34px!important;height:34px;padding:0!important;margin:0!important;background:#1a1816!important;color:#ddd!important}
.s106-fade{position:absolute;inset:0;background:radial-gradient(circle at 50% 42%,transparent 0 32%,rgba(0,0,0,.1) 58%,rgba(0,0,0,.55) 100%);pointer-events:none;z-index:2}
@media(max-width:380px){.s106-brand{font-size:12px}.s106-pill{font-size:10px;padding:6px 7px}.s106-joy{bottom:100px}.s106-actions{bottom:103px}}
`;
function addStyle(){if(document.getElementById('s106css'))return;const s=document.createElement('style');s.id='s106css';s.textContent=WORLD_CSS;document.head.appendChild(s)}
function esc106(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
let root,canvas,ctx,w,h,raf,world={x:0,y:0,dirX:0,dirY:0,district:'ЦЕНТР СДОЛАРС',name:'Игрок',hp:120,maxHp:120,coins:0,level:1};
const zones=[
 {id:'market',name:'Рыночная площадь',x:.18,y:.27,w:.25,h:.20,icon:'🏪',desc:'Торговцы снаряжением и обмен монет.',action:'market'},
 {id:'arena',name:'Боевая арена',x:.58,y:.22,w:.25,h:.22,icon:'⚔️',desc:'Здесь решают споры кулаками и сталью.',action:'arena'},
 {id:'guild',name:'Гильдейский двор',x:.12,y:.58,w:.28,h:.22,icon:'⚜️',desc:'Гильдии, приглашения и управление составом.',action:'guild'},
 {id:'people',name:'Площадь людей',x:.59,y:.59,w:.28,h:.22,icon:'👥',desc:'Жители и бойцы Сдоларса.',action:'people'}
];
const npcs=[{x:.48,y:.44,name:'Кузнец',icon:'🧔'},{x:.72,y:.48,name:'Стражник',icon:'🛡️'},{x:.31,y:.70,name:'Торговец',icon:'🧑‍🌾'}];
function resize(){const d=devicePixelRatio||1;w=innerWidth;h=innerHeight;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}
function roundRect(c,x,y,ww,hh,r){c.beginPath();c.roundRect(x,y,ww,hh,r);c.fill()}
function drawBuilding(z){const x=z.x*w,y=z.y*h,ww=z.w*w,hh=z.h*h;ctx.fillStyle='#171614';roundRect(ctx,x,y,ww,hh,10);ctx.strokeStyle='#5c492d';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#28231c';ctx.beginPath();ctx.moveTo(x-5,y+8);ctx.lineTo(x+ww/2,y-18);ctx.lineTo(x+ww+5,y+8);ctx.closePath();ctx.fill();ctx.strokeStyle='#4e402b';ctx.stroke();ctx.font=Math.max(18,w*.045)+'px sans-serif';ctx.textAlign='center';ctx.fillStyle='#d6b777';ctx.fillText(z.icon,x+ww/2,y+hh*.55);ctx.font='700 '+Math.max(10,w*.028)+'px Arial';ctx.fillStyle='#d7d0c4';ctx.fillText(z.name,x+ww/2,y+hh*.83)}
function draw(){ctx.clearRect(0,0,w,h);
 let g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#151716');g.addColorStop(.48,'#22201b');g.addColorStop(1,'#0b0d0d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 // distant skyline
 ctx.fillStyle='#101212';for(let i=0;i<12;i++){let bw=25+(i%4)*13,bh=70+(i*31)%95,x=i*(w/10)-20;ctx.fillRect(x,115,bw,bh);}
 // roads
 ctx.fillStyle='#111212';ctx.beginPath();ctx.moveTo(w*.42,105);ctx.lineTo(w*.58,105);ctx.lineTo(w*.72,h);ctx.lineTo(w*.25,h);ctx.closePath();ctx.fill();ctx.strokeStyle='#37332c';ctx.lineWidth=2;ctx.stroke();
 ctx.strokeStyle='#5a4a31';ctx.lineWidth=1;ctx.setLineDash([10,12]);ctx.beginPath();ctx.moveTo(w*.5,120);ctx.lineTo(w*.49,h);ctx.stroke();ctx.setLineDash([]);
 zones.forEach(drawBuilding);
 // trees
 for(let i=0;i<10;i++){let tx=(i*83+27)%w,ty=190+(i*71)%(Math.max(150,h-300));ctx.fillStyle='#30271c';ctx.fillRect(tx-2,ty,4,17);ctx.fillStyle='#1e3026';ctx.beginPath();ctx.arc(tx,ty,13,0,Math.PI*2);ctx.fill()}
 // NPCs
 npcs.forEach((n,i)=>{let x=n.x*w,y=n.y*h+Math.sin(performance.now()/500+i)*2;ctx.font='25px sans-serif';ctx.textAlign='center';ctx.fillText(n.icon,x,y);ctx.font='10px Arial';ctx.fillStyle='#aaa298';ctx.fillText(n.name,x,y+15)});
 // player shadow + character
 const px=w*.5+world.x,py=h*.48+world.y;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(px,py+19,17,6,0,0,Math.PI*2);ctx.fill();ctx.font='37px sans-serif';ctx.textAlign='center';ctx.fillText('🧍',px,py+12);ctx.font='700 10px Arial';ctx.fillStyle='#e0c487';ctx.fillText(world.name,px,py+29);
 // subtle movement particles
 for(let i=0;i<6;i++){let a=performance.now()/1200+i;let sx=px+Math.cos(a*1.7+i)*18,sy=py+Math.sin(a*1.3+i)*10;ctx.fillStyle='#a47c3c55';ctx.fillRect(sx,sy,2,2)}
 raf=requestAnimationFrame(draw)}
function hint(text){const e=document.querySelector('.s106-hint');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(hint.t);hint.t=setTimeout(()=>e.classList.remove('show'),2200)}
function openZone(z){const card=document.createElement('div');card.className='s106-card';card.innerHTML=`<button class="s106-close">×</button><h3>${z.icon} ${esc106(z.name)}</h3><p>${esc106(z.desc)}</p><button class="s106-enter">Войти</button>`;root.appendChild(card);card.querySelector('.s106-close').onclick=()=>card.remove();card.querySelector('.s106-enter').onclick=()=>{card.remove();try{window.TerritoryS102?.open(z.action)}catch(e){alert(e.message)}}}
function pointer(x,y){for(const z of zones){if(x>=z.x*w&&x<=((z.x+z.w)*w)&&y>=z.y*h&&y<=((z.y+z.h)*h))return z}return null}
function move(dx,dy){world.x=Math.max(-w*.18,Math.min(w*.18,world.x+dx));world.y=Math.max(-h*.12,Math.min(h*.12,world.y+dy));}
function setupTouch(){let dragging=false,startX=0,startY=0;const joy=root.querySelector('.s106-joy'),stick=root.querySelector('.s106-stick');joy.addEventListener('pointerdown',e=>{dragging=true;joy.setPointerCapture(e.pointerId);startX=e.clientX;startY=e.clientY});joy.addEventListener('pointermove',e=>{if(!dragging)return;let dx=e.clientX-startX,dy=e.clientY-startY,len=Math.hypot(dx,dy)||1,max=31;if(len>max){dx=dx/len*max;dy=dy/len*max}stick.style.transform=`translate(${dx}px,${dy}px)`;move(dx*.10,dy*.10)});joy.addEventListener('pointerup',()=>{dragging=false;stick.style.transform='translate(0,0)'});joy.addEventListener('pointercancel',()=>{dragging=false;stick.style.transform='translate(0,0)'});
 canvas.addEventListener('pointerup',e=>{const z=pointer(e.clientX,e.clientY);if(z)openZone(z);else {world.x=(e.clientX-w/2)*.08;world.y=(e.clientY-h*.48)*.06;hint('Ты переместился по Сдоларсу')}});
 root.querySelector('[data-w="city"]').onclick=()=>{try{window.TerritoryS102?.open('city')}catch(e){}};
 root.querySelector('[data-w="char"]').onclick=()=>{try{window.TerritoryS102?.open('char')}catch(e){}};
 root.querySelector('[data-w="quest"]').onclick=()=>{try{window.TerritoryS102?.open('quests')}catch(e){}};
}
async function loadStats(){try{const d=await fetch('/api/character?id='+encodeURIComponent(window.TerritoryS102?.playerId?.()||localStorage.getItem('territory_player_id')||''));const j=await d.json();const s=j.stats;if(s){world.hp=s.hp??s.maxHp??120;world.maxHp=s.maxHp??120;world.coins=s.coins??0;world.level=s.level??1;world.name=(window.Telegram?.WebApp?.initDataUnsafe?.user?.first_name)||'Игрок';const hp=document.querySelector('[data-hud="hp"]');if(hp)hp.textContent=`❤️ ${world.hp}/${world.maxHp}`;const coin=document.querySelector('[data-hud="coin"]');if(coin)coin.textContent=`🪙 ${world.coins}`;const lev=document.querySelector('[data-hud="lvl"]');if(lev)lev.textContent=`УР ${world.level}`}}catch(e){}}
function build(){if(document.getElementById('s106-world'))return;addStyle();root=document.createElement('div');root.id='s106-world';root.innerHTML=`<canvas id="s106-canvas"></canvas><div class="s106-fade"></div><div class="s106-hud"><div class="s106-brand">TERRITORY</div><div class="s106-stats"><span class="s106-pill s106-hp" data-hud="hp">❤️ —</span><span class="s106-pill s106-coin" data-hud="coin">🪙 —</span><span class="s106-pill" data-hud="lvl">УР —</span></div></div><div class="s106-district">⚑ ${world.district}</div><div class="s106-actions"><button class="s106-action" data-w="char">🧍</button><button class="s106-action" data-w="quest">📜</button><button class="s106-action" data-w="city">🗺️</button></div><div class="s106-joy"><div class="s106-stick"></div></div><div class="s106-hint">Сдоларс живёт своей жизнью</div>`;document.body.appendChild(root);canvas=root.querySelector('#s106-canvas');ctx=canvas.getContext('2d');resize();addEventListener('resize',resize);setupTouch();loadStats();draw()}
function init(){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build()}
// delay lets the existing S102/S103 modules create their API facade first
setTimeout(init,120);
})();
