(()=>{
const K='territory_s83_lobby'; const load=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch(e){return {}}}; const save=x=>localStorage.setItem(K,JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tg(){return window.Telegram&&Telegram.WebApp?Telegram.WebApp:null} function me(){const w=tg(),u=w&&w.initDataUnsafe&&w.initDataUnsafe.user;return {id:u&&String(u.id)||'',name:u?((u.first_name||'')+' '+(u.last_name||'')).trim()||u.username||'Игрок':'Игрок'}}
async function api(path,opt={}){let base=localStorage.getItem('territory_server_url')||'';if(!base)return null;const w=tg(),h=Object.assign({'content-type':'application/json'},opt.headers||{});if(w&&w.initData)h['x-telegram-init-data']=w.initData;try{const r=await fetch(base+path,{...opt,headers:h});return await r.json()}catch(e){return null}}
async function render(q=''){const a=load(),r=await api('/api/players?q='+encodeURIComponent(q));let list=r&&r.players||[];const h=`<div class="s83hero"><b>🌐 Игроки онлайн</b><small>Найди игрока, открой профиль, добавь в друзья или пригласи в клан.</small></div><input id="s83q" class="s83input" placeholder="Поиск по имени или ID" value="${esc(q)}"><button class="s83btn" onclick="s83Search()">🔎 Найти</button><div id="s83list">${list.length?list.map(p=>`<div class="s83player"><div><b>${esc(p.name)}</b><small>${esc(p.clan||'Без клана')} · Ур. ${p.level} ${p.online?'🟢 онлайн':'⚪ офлайн'}</small></div><button class="s83mini" onclick="s83Profile('${esc(p.id)}')">Профиль</button></div>`).join(''):'<div class="s83empty">Игроки не найдены.</div>'}</div>`; if(typeof panel==='function')panel('🌐 Лобби',h);else if(typeof openSheet==='function')openSheet('Лобби',h)}
window.s83Search=()=>render(document.getElementById('s83q')?.value||'');
window.s83Profile=async id=>{const r=await api('/api/player?id='+encodeURIComponent(id));if(!r||!r.ok)return alert('Профиль не найден');const p=r.player;const h=`<div class="s83hero"><b>👤 ${esc(p.name)}</b><small>${p.online?'🟢 Сейчас онлайн':'⚪ Сейчас офлайн'}</small></div><div class="s83grid"><div><small>Уровень</small><b>${p.level}</b></div><div><small>Опыт</small><b>${p.xp}</b></div></div><div class="s83card">🛡️ Клан: <b>${esc(p.clan||'Без клана')}</b><br><small>ID: ${esc(p.id)}</small></div><button class="s83btn" onclick="s83Friend('${esc(p.id)}')">🤝 Добавить в друзья</button>${p.clan?`<button class="s83btn" onclick="s83Invite('${esc(p.id)}')">🛡️ Пригласить в свой клан</button>`:''}<button class="s83btn primary" onclick="s83Challenge('${esc(p.id)}')">⚔️ Вызвать на PvP</button>`;if(typeof panel==='function')panel('Профиль игрока',h);else openSheet('Профиль игрока',h)};
window.s83Friend=async id=>{const r=await api('/api/friends',{method:'POST',body:JSON.stringify({targetId:id})});alert(r&&r.ok?'🤝 Запрос отправлен.':'⚠️ Не удалось отправить запрос.');};
window.s83Invite=async id=>{const r=await api('/api/clan/invite',{method:'POST',body:JSON.stringify({targetId:id})});alert(r&&r.ok?'🛡️ Приглашение отправлено.':'⚠️ Приглашение не отправлено.');};
window.s83Challenge=id=>{if(window.s82StartSearch){s82StartSearch();alert('🎯 Запустил поиск PvP-соперника. Сервер подберёт подходящего игрока.')}else alert('Сначала открой режим поиска PvP.');};
window.s83Lobby=()=>render('');
const old=window.openSheet;window.openSheet=function(title){if(title==='Лобби'||title==='Игроки онлайн')return s83Lobby();return old&&old.apply(this,arguments)};
setTimeout(()=>{const nav=[...document.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='Аккаунт');if(nav&&!document.getElementById('s83LobbyBtn')){const b=document.createElement('button');b.id='s83LobbyBtn';b.className=nav.className;b.innerHTML='<span>🌐</span>Лобби';b.onclick=s83Lobby;nav.parentNode.insertBefore(b,nav.nextSibling)}},1000);
})();
