(()=>{'use strict';
const API=location.origin,tg=window.Telegram?.WebApp;
const me=()=>String(tg?.initDataUnsafe?.user?.id||localStorage.getItem('territory_player_id')||localStorage.getItem('playerId')||'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function req(path,opt={}){const o={...opt,headers:{'content-type':'application/json',...(opt.headers||{})}};if(tg?.initData)o.headers['x-telegram-init-data']=tg.initData;const r=await fetch(API+path,o),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Ошибка запроса');return j}
function style(){if(document.getElementById('s84-guild-style'))return;const s=document.createElement('style');s.id='s84-guild-style';s.textContent=`#s84-guild-btn{position:fixed;right:12px;bottom:92px;z-index:9998;border:1px solid #8b6a2b;background:linear-gradient(180deg,#3b2b18,#1b1510);color:#f5d58b;border-radius:12px;padding:10px 13px;font-weight:800;box-shadow:0 5px 18px #0008}#s84-guild{position:fixed;inset:0;z-index:9999;display:none;background:#000b;backdrop-filter:blur(5px)}#s84-guild.on{display:block}#s84-card{position:absolute;left:8px;right:8px;top:7%;bottom:7%;overflow:auto;border:1px solid #765522;border-radius:16px;background:linear-gradient(145deg,#19150f,#0d1014);color:#eee;padding:14px;box-shadow:0 20px 60px #000c;font-family:inherit}#s84-card h2{margin:0;color:#e8c16b;font-size:22px}#s84-close{float:right;border:0;background:#31271d;color:#fff;border-radius:8px;padding:6px 10px}.s84-stat{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.s84-stat b,.s84-member{background:#151a20;border:1px solid #30363d;border-radius:10px;padding:8px}.s84-stat b{color:#f0d38a}.s84-actions{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.s84-actions button,#s84-card button{border:1px solid #765522;background:#282018;color:#f6d994;border-radius:9px;padding:8px 10px}.s84-input{width:100%;box-sizing:border-box;margin:5px 0;padding:9px;border-radius:8px;border:1px solid #444;background:#101318;color:#fff}.s84-msg{margin:8px 0;color:#ffcf70}.s84-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.s84-muted{color:#9da4ad;font-size:12px}@media(max-width:430px){.s84-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function shell(){if(document.getElementById('s84-guild'))return;style();const b=document.createElement('button');b.id='s84-guild-btn';b.textContent='⚔ ГИЛЬДИЯ';b.onclick=open;document.body.appendChild(b);const w=document.createElement('div');w.id='s84-guild';w.innerHTML='<div id="s84-card"><button id="s84-close">✕</button><h2>⚔ Гильдия Sdolars</h2><div id="s84-body">Загрузка...</div></div>';document.body.appendChild(w);document.getElementById('s84-close').onclick=()=>w.classList.remove('on')}
async function open(){shell();document.getElementById('s84-guild').classList.add('on');await render()}
async function render(){const root=document.getElementById('s84-body'),id=me();if(!id){root.innerHTML='<div class="s84-msg">Открой игру из Telegram.</div>';return}
try{const p=await req('/api/profile?id='+encodeURIComponent(id)).catch(()=>({profile:{name:'Игрок',clan:''}}));
if(!p.profile?.clan){root.innerHTML='<div class="s84-msg">Ты пока не состоишь в гильдии.</div><div class="s84-grid"><div><b>Создать гильдию</b><input id="gname" class="s84-input" placeholder="Название"><input id="gtag" class="s84-input" placeholder="Тег 2–8 символов"><button onclick="window.s84Create()">Создать</button></div><div><b>Найти гильдию</b><input id="gsearch" class="s84-input" placeholder="Название или тег"><button onclick="window.s84Find()">Найти</button><div id="glist"></div></div></div>';return}
const c=(await req('/api/clan?id='+encodeURIComponent(p.profile.clan))).clan;
root.innerHTML='<div class="s84-stat"><b>LV '+c.level+'</b><b>👥 '+c.members.length+'/50</b><b>⭐ '+c.reputation+'</b><b>🏦 '+c.treasury+'</b><b>XP '+c.xp+'</b></div><div class="s84-muted">['+esc(c.tag)+'] '+esc(c.name)+'</div><div class="s84-actions"><button onclick="window.s84Refresh()">↻ Обновить</button><button onclick="window.s84Leave()">Покинуть</button></div><h3>Состав</h3>'+c.members.map(m=>'<div class="s84-member"><span>⚔ '+esc(m.name)+' <span class="s84-muted">'+esc(m.role)+' · LV'+m.level+'</span></span>'+(c.ownerId===id&&m.id!==id?'<button onclick="window.s84Role(\''+esc(m.id)+'\')">Роль</button>':'')+'</div>').join('');
}catch(e){root.innerHTML='<div class="s84-msg">'+esc(e.message)+'</div>'}}
window.s84Create=async()=>{try{await req('/api/clan/create',{method:'POST',body:JSON.stringify({playerId:me(),name:document.getElementById('gname').value,tag:document.getElementById('gtag').value,playerName:tg?.initDataUnsafe?.user?.first_name||'Игрок'})});await render()}catch(e){alert(e.message)}};
window.s84Find=async()=>{try{const j=await req('/api/clans?q='+encodeURIComponent(document.getElementById('gsearch').value)),el=document.getElementById('glist');el.innerHTML=j.clans.length?j.clans.map(c=>'<div class="s84-member"><span>['+esc(c.tag)+'] '+esc(c.name)+' · '+c.members.length+'/50</span><button onclick="window.s84Join(\''+esc(c.id)+'\')">Вступить</button></div>').join(''):'Ничего не найдено'}catch(e){alert(e.message)}};
window.s84Join=async cid=>{try{await req('/api/clan/join',{method:'POST',body:JSON.stringify({playerId:me(),clanId:cid,playerName:tg?.initDataUnsafe?.user?.first_name||'Игрок'})});await render()}catch(e){alert(e.message)}};
window.s84Leave=async()=>{if(!confirm('Покинуть гильдию?'))return;try{await req('/api/clan/leave',{method:'POST',body:JSON.stringify({playerId:me()})});await render()}catch(e){alert(e.message)}};
window.s84Role=async mid=>{const role=prompt('Роль: officer, scout или warrior','warrior');if(!role)return;try{await req('/api/clan/role',{method:'POST',body:JSON.stringify({playerId:me(),memberId:mid,role})});await render()}catch(e){alert(e.message)}};
window.s84Refresh=render;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',shell);else shell();
})();