
(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tg=()=>window.Telegram&&Telegram.WebApp?Telegram.WebApp:null;const me=()=>{const u=tg()?.initDataUnsafe?.user;return{id:u&&String(u.id)||'',name:u?((u.first_name||'')+' '+(u.last_name||'')).trim()||u.username||'Игрок':'Игрок'}};
async function api(path,opt={}){const base=localStorage.getItem('territory_server_url')||'';if(!base)return null;const w=tg(),headers=Object.assign({'content-type':'application/json'},opt.headers||{});if(w?.initData)headers['x-telegram-init-data']=w.initData;try{return await (await fetch(base+path,{...opt,headers})).json()}catch(e){return null}}
let tab='friends',data={friends:[],requests:[],invites:[]};
async function load(){const r=await api('/api/social?id='+encodeURIComponent(me().id));if(r?.ok)data=r;render()}
function render(){let h='<div class="s84hero"><b>🤝 Друзья и общение</b><span class="s84small">Игроки, сообщения, вызовы и приглашения — в одном месте.</span></div><div class="s84tabs">'+[['friends','👥 Друзья'],['requests','📨 Заявки'],['invites','🛡️ Клан'],['chat','💬 Чат']].map(x=>`<button class="s84tab ${tab===x[0]?'sel':''}" onclick="s84Tab('${x[0]}')">${x[1]}</button>`).join('')+'</div>';
if(tab==='friends')h+=`<div class="s84card">${data.friends.length?data.friends.map(p=>`<div class="s84row"><span>👤 <b>${esc(p.name)}</b><br><span class="s84small">${p.online?'🟢 онлайн':'⚪ офлайн'} · Ур. ${p.level}</span></span><span><button class="s84mini" onclick="s84Chat('${esc(p.id)}','${esc(p.name)}')">💬</button> <button class="s84mini" onclick="s84Remove('${esc(p.id)}')">✕</button></span></div>`).join(''):'Нет друзей. Открой «Лобби» и добавь игроков.'}</div>`;
if(tab==='requests')h+=`<div class="s84card">${data.requests.length?data.requests.map(p=>`<div class="s84row"><span>👤 <b>${esc(p.name)}</b><br><span class="s84small">Ур. ${p.level}</span></span><span><button class="s84mini" onclick="s84Accept('${esc(p.id)}')">✅</button><button class="s84mini" onclick="s84Decline('${esc(p.id)}')">✕</button></span></div>`).join(''):'Новых заявок нет.'}</div>`;
if(tab==='invites')h+=`<div class="s84card">${data.invites.length?data.invites.map(c=>`<div class="s84row"><span>🛡️ <b>${esc(c.name)}</b> <span class="s84small">[${esc(c.tag)}]</span></span><span><button class="s84mini" onclick="s84ClanAccept('${esc(c.id)}')">Войти</button><button class="s84mini" onclick="s84ClanDecline('${esc(c.id)}')">✕</button></span></div>`).join(''):'Клановых приглашений нет.'}</div>`;
if(tab==='chat')h+='<div class="s84card"><input id="s84chatId" class="s84input" placeholder="ID друга"><button class="s84btn" onclick="s84Chat(document.getElementById(\'s84chatId\').value,\'Друг\')">Открыть чат</button></div>';
if(typeof panel==='function')panel('🤝 Социальный центр',h);else if(typeof openSheet==='function')openSheet('🤝 Социальный центр',h)}
window.s84Tab=t=>{tab=t;load()};window.s84Accept=async id=>{await api('/api/friends/accept',{method:'POST',body:JSON.stringify({fromId:id})});load()};window.s84Decline=async id=>{await api('/api/friends/decline',{method:'POST',body:JSON.stringify({fromId:id})});load()};window.s84Remove=async id=>{await api('/api/friends/remove',{method:'POST',body:JSON.stringify({targetId:id})});load()};
window.s84ClanAccept=async id=>{const r=await api('/api/clan/invite/accept',{method:'POST',body:JSON.stringify({clanId:id})});alert(r?.ok?'🛡️ Ты вступил в клан!':'⚠️ '+(r?.error||'Ошибка'));load()};window.s84ClanDecline=async id=>{await api('/api/clan/invite/decline',{method:'POST',body:JSON.stringify({clanId:id})});load()};
window.s84Chat=async(id,name)=>{if(!id)return;let r=await api('/api/messages?id='+encodeURIComponent(me().id)+'&with='+encodeURIComponent(id));let msgs=r?.messages||[];let h=`<div class="s84hero"><b>💬 ${esc(name)}</b><span class="s84small">Личные сообщения</span></div><div class="s84chat" id="s84msgs">${msgs.map(m=>`<div class="s84msg ${m.from===me().id?'me':''}">${esc(m.text)}<div class="s84small">${new Date(m.ts).toLocaleTimeString()}</div></div>`).join('')}</div><input id="s84text" class="s84input" placeholder="Сообщение"><button class="s84btn primary" onclick="s84Send('${esc(id)}','${esc(name)}')">Отправить</button><button class="s84btn" onclick="s84Tab('friends')">← Назад</button>`;panel('💬 Чат',h)};
window.s84Send=async(id,name)=>{const el=document.getElementById('s84text'),text=el?.value.trim();if(!text)return;const r=await api('/api/messages',{method:'POST',body:JSON.stringify({toId:id,text})});if(!r?.ok)return alert('⚠️ Не удалось отправить');s84Chat(id,name)};
function add(){if(document.getElementById('s84SocialBtn'))return;const b=document.createElement('button');b.id='s84SocialBtn';b.className='bottomBtn';b.innerHTML='<span>🤝</span>Друзья';b.onclick=()=>load();const nav=document.querySelector('.bottomNav');if(nav)nav.insertBefore(b,nav.lastElementChild||null)}add();document.addEventListener('DOMContentLoaded',add);setTimeout(add,900);window.s84Social=load;
})();
