/* Territory G63 — unified Quest Journal + Alex interaction bridge.
   Built on G62. City artwork, PvE and Arena are untouched. */
(function(){'use strict';
 const $=s=>document.querySelector(s);
 function state(){try{return window.TerritoryCore?.getState?.()||window.TerritoryStore?.getState?.()||{};}catch(e){return {};}}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
 function inject(){if($('#territory-g63-quests-css'))return;const c=document.createElement('style');c.id='territory-g63-quests-css';c.textContent=`
 #tgQuestJournal{position:fixed;inset:0;z-index:100003;display:none;align-items:flex-end;justify-content:center;background:rgba(2,7,12,.78);backdrop-filter:blur(5px)}
 #tgQuestJournal.show{display:flex}#tgQuestJournal .qj-card{width:min(720px,100%);max-height:88vh;overflow:auto;border:1px solid #9b7545;border-radius:20px 20px 0 0;background:linear-gradient(180deg,#15232c,#081117);color:#f4ead7;padding:14px;box-sizing:border-box;box-shadow:0 -18px 55px #000b}
 .qj-head{display:flex;align-items:center;gap:10px}.qj-head h2{margin:0;flex:1;font:700 20px Georgia,serif;color:#f0d092}.qj-close{border:1px solid #80603d;background:#18242a;color:#f6dfae;border-radius:10px;padding:8px 12px;font-weight:800}.qj-cardbox{border:1px solid #354a55;border-radius:14px;background:#0e1a21;margin-top:10px;padding:11px}.qj-title{font-weight:900}.qj-muted{font-size:11px;color:#aebbc2;margin-top:3px}.qj-row{display:grid;grid-template-columns:34px 1fr auto;gap:9px;align-items:center}.qj-ico{font-size:25px;text-align:center}.qj-bar{height:7px;border-radius:8px;background:#071016;border:1px solid #2d4049;overflow:hidden;margin-top:7px}.qj-bar i{display:block;height:100%;background:#d4ad55}.qj-reward{font-size:10px;color:#e6c77f;text-align:right;white-space:nowrap}.qj-done{border-color:#5d805d}.qj-btn{margin-top:10px;width:100%;border:1px solid #a47a40;border-radius:10px;background:linear-gradient(#593b24,#2d2119);color:#f6dfb0;padding:10px;font-weight:900}.qj-alex{border-color:#9b7545;background:linear-gradient(135deg,#1d292e,#0c171c)}
 `;document.head.appendChild(c)}
 function open(){inject();let o=$('#tgQuestJournal');if(!o){o=document.createElement('div');o.id='tgQuestJournal';o.innerHTML='<div class="qj-card"><div class="qj-head"><h2>📜 Журнал заданий</h2><button class="qj-close">✕</button></div><div id="qjBody"></div></div>';document.body.appendChild(o);o.querySelector('.qj-close').onclick=()=>o.classList.remove('show');o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show')})}render(o.querySelector('#qjBody'));o.classList.add('show')}
 function render(body){const s=state();const quests=Array.isArray(s.quests)?s.quests:[];const defs=[{id:'pve',ico:'⚔️',title:'Городской боец',desc:'Победи противников в обычном PvE.',goal:5,reward:120},{id:'arena',ico:'🏟️',title:'Испытание Арены',desc:'Побеждай в отдельной PvP-Арене.',goal:3,reward:100},{id:'buy',ico:'🪙',title:'Торговец',desc:'Купи предмет на рынке.',goal:1,reward:80},{id:'repair',ico:'🔨',title:'Кузнец',desc:'Отремонтируй экипировку.',goal:1,reward:60}];
 let html='<div class="qj-cardbox qj-alex"><div class="qj-row"><div class="qj-ico">🧔</div><div><div class="qj-title">Alex — Хранитель Sdolars</div><div class="qj-muted">Городская цепочка заданий и поручений. Продолжение открывается через события города.</div></div><div class="qj-reward">⭐ '+(s.cityRep||0)+' реп.</div></div></div>';
 html+=defs.map(d=>{const q=quests.find(x=>x.id===d.id);const v=Math.min(d.goal,Number(q?.value||0));const done=v>=d.goal;return `<div class="qj-cardbox ${done?'qj-done':''}"><div class="qj-row"><div class="qj-ico">${d.ico}</div><div><div class="qj-title">${d.title}</div><div class="qj-muted">${d.desc}</div><div class="qj-bar"><i style="width:${Math.round(v/d.goal*100)}%"></i></div><div class="qj-muted">${v}/${d.goal}</div></div><div class="qj-reward">+${d.reward} 🪙</div></div></div>`}).join('');
 if(!quests.length)html+='<div class="qj-cardbox"><div class="qj-muted">Новые задания появятся после первых действий в городе.</div></div>';
 body.innerHTML=html;}
 function alexHit(){if($('#territory-g63-alex-hit'))return;const b=document.createElement('button');b.id='territory-g63-alex-hit';b.type='button';b.setAttribute('aria-label','Поговорить с Alex');document.body.appendChild(b);const c=document.createElement('style');c.id='territory-g63-alex-hit-css';c.textContent=`body:has(#home.active) #territory-g63-alex-hit{display:block!important;position:absolute!important;z-index:100!important;left:4%!important;top:43%!important;width:43%!important;height:38%!important;border:0!important;background:transparent!important;padding:0!important;opacity:0!important;pointer-events:auto!important;touch-action:manipulation}`;document.head.appendChild(c);b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(typeof window.TerritoryAlexTalk==='function')window.TerritoryAlexTalk();else document.querySelector('.guard-label')?.click()},{capture:true})}
 document.addEventListener('click',e=>{const q=e.target.closest('[data-ui="quests"],[data-g63="quests"],#g40-quests');if(q){e.preventDefault();e.stopImmediatePropagation();open()}},true);
 document.addEventListener('DOMContentLoaded',()=>{alexHit()});if(document.readyState!=='loading')alexHit();
 window.TerritoryQuests={open,refresh:()=>{const b=$('#qjBody');if(b)render(b)}};
})();
