/* Territory G41 GLOBAL — one integrated gameplay pass over the preserved G40 City. */
(function(){'use strict';
 const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const KEY='territory_save_v1';
 const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
 let st=load();
 const defaults={name:'SSS',level:1,exp:0,maxExp:100,hp:120,maxHp:120,coins:1000,gems:25,energy:100,combatStone:20,strength:5,agility:5,defense:0,endurance:12,weaponMastery:1,freePoints:0,weapon:'Кулаки',bonusDamage:0,inventory:[],equipped:{},durability:{},pveProgress:0,cityLevel:1,pveWins:0,hunger:100,lang:'ru',dailyClaim:'',vipDays:0};
 st={...defaults,...st,equipped:{...defaults.equipped,...(st.equipped||{})},durability:{...defaults.durability,...(st.durability||{})}};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(st));localStorage.setItem('territory_save',JSON.stringify(st))}catch(e){}; if(typeof window.render==='function')window.render(); updateHud();};
 function updateHud(){const map={playerName:st.name,level:st.level,coins:st.coins,gems:st.gems};Object.entries(map).forEach(([id,v])=>{const e=$('#'+id);if(e)e.textContent=v});}
 function toast(t){let x=$('#tgToast');if(!x){x=document.createElement('div');x.id='tgToast';x.className='tg-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)}
 function overlay(id,title,body){let o=$('#'+id);if(!o){o=document.createElement('div');o.id=id;o.className='tg-overlay';o.innerHTML='<div class="tg-panel"><div class="tg-head"><h2></h2><button class="tg-x">✕</button></div><div class="tg-body"></div></div>';document.body.appendChild(o);o.querySelector('.tg-x').onclick=()=>o.classList.remove('show');o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show')})}o.querySelector('h2').textContent=title;o.querySelector('.tg-body').innerHTML=body;o.classList.add('show');return o}
 const items=[
  {id:'axe',name:'Боевой топор',icon:'🪓',damage:12,cost:300,type:'weapon'},
  {id:'sword',name:'Стальной меч',icon:'⚔️',damage:18,cost:650,type:'weapon'},
  {id:'helm',name:'Стальной шлем',icon:'🪖',defense:4,cost:500,type:'armor'},
  {id:'armor',name:'Волчья броня',icon:'🥋',defense:7,cost:900,type:'armor'}
 ];
 function addItem(it){st.inventory.push(it.id);if(it.type==='weapon'&&!st.weapon)st.weapon=it.name;st.durability[it.id]=300;save()}
 function profile(){const d={power:Math.round(st.strength*2+st.agility*1.5+st.defense*2+st.endurance+st.weaponMastery*3+st.bonusDamage),crit:Math.min(60,st.strength*2),dodge:Math.min(45,Math.round(st.agility*1.5)),damage:Math.max(1,5+st.strength+st.weaponMastery+st.bonusDamage),block:Math.min(70,Math.round(st.defense*1.8))};overlay('tgProfile','👤 Профиль персонажа',`<div class="tg-card tg-row"><div class="tg-icon">🧔</div><div class="tg-grow"><b>${esc(st.name)}</b><div class="tg-muted">Уровень ${st.level} · XP ${st.exp}/${st.maxExp}</div><div class="tg-bar"><i style="width:${Math.min(100,st.exp/st.maxExp*100)}%"></i></div></div></div><div class="tg-grid">${[['💪','Сила',st.strength],['🏃','Ловкость',st.agility],['🛡️','Защита',st.defense],['❤️','Выносливость',st.endurance],['⚔️','Мастерство',st.weaponMastery],['🏆','Мощь',d.power],['💥','Крит',d.crit+'%'],['🌀','Уклонение',d.dodge+'%'],['⚔️','Урон',d.damage],['🛡️','Блок',d.block+'%']].map(x=>`<div class="tg-stat"><b>${x[0]} ${x[2]}</b><small>${x[1]}</small></div>`).join('')}</div><div class="tg-card"><b>Свободные очки: ${st.freePoints}</b><div class="tg-grid" style="margin-top:8px">${[['strength','Сила'],['agility','Ловкость'],['defense','Защита'],['endurance','Выносливость'],['weaponMastery','Мастерство']].map(x=>`<button class="tg-btn" data-addstat="${x[0]}" ${st.freePoints<1?'disabled':''}>+ ${x[1]}</button>`).join('')}</div></div>`)}
 function inventory(){const counts={};st.inventory.forEach(id=>counts[id]=(counts[id]||0)+1);const list=Object.keys(counts).length?Object.entries(counts).map(([id,n])=>{const it=items.find(x=>x.id===id)||{id,name:id,icon:'📦'};const dur=st.durability[id]??300;return `<div class="tg-card tg-item"><div class="tg-icon">${it.icon}</div><div class="tg-grow"><b>${esc(it.name)}</b><div class="tg-muted">${it.damage?'Урон +'+it.damage:''}${it.defense?'Защита +'+it.defense:''}</div><div class="tg-tag">Прочность ${dur}/300</div></div><button class="tg-btn" data-equip="${id}">${st.equipped[id]?'Снять':'Надеть'}</button></div>`}).join(''):'<div class="tg-card tg-muted">Инвентарь пока пуст.</div>';overlay('tgInv','🎒 Инвентарь',`<div class="tg-card"><b>Оружие: ${esc(st.weapon)}</b><div class="tg-muted">Урон +${st.bonusDamage}</div></div>${list}`)}
 function market(){overlay('tgMarket','🛒 Рынок',`<div class="tg-card"><b>Репутация торговца</b><div class="tg-muted">Покупай оружие и броню. Прочность каждой вещи — 300 ударов.</div></div>${items.map(it=>`<div class="tg-card tg-item"><div class="tg-icon">${it.icon}</div><div class="tg-grow"><b>${it.name}</b><div class="tg-muted">${it.damage?'Урон +'+it.damage:''} ${it.defense?'Защита +'+it.defense:''} · ${it.cost} 🪙</div></div><button class="tg-btn" data-buyitem="${it.id}">Купить</button></div>`).join('')}`)}
 function bonuses(){const day=new Date().toISOString().slice(0,10);overlay('tgBonus','🎁 Бонусы',`<div class="tg-card"><b>Ежедневный бонус</b><p class="tg-muted">+100 🪙 · +5 ⚔️ Боевых камней</p><button class="tg-btn gold" data-daily ${st.dailyClaim===day?'disabled':''}>${st.dailyClaim===day?'Уже получено':'Забрать бонус'}</button></div><div class="tg-card"><b>Текущие ресурсы</b><div class="tg-muted">⚡ ${st.energy}/200 · ⚔️ ${st.combatStone}</div></div>`)}
 function events(){overlay('tgEvents','📅 События',`<div class="tg-card"><b>Город живёт</b><p class="tg-muted">Встречи Alex, караваны, торговые случаи и городские задания уже работают в City.</p><button class="tg-btn" data-eventclaim>Проверить события</button></div><div class="tg-card"><b>Задание Alex</b><p class="tg-muted">Следи за городом и помогай при тревогах.</p></div>`)}
 function vip(){overlay('tgVip','👑 VIP',`<div class="tg-card"><b>VIP ${st.vipDays>0?'активен':'не активен'}</b><p class="tg-muted">В прототипе VIP даёт дополнительный ежедневный бонус. Покупки за реальные деньги здесь не подключены.</p><button class="tg-btn" data-vip>Активировать тестовый VIP на 1 день</button></div>`)}
 function tavern(){overlay('tgTavern','🍺 Таверна',`<div class="tg-card"><b>Голод: ${st.hunger}%</b><div class="tg-bar"><i style="width:${st.hunger}%"></i></div><p class="tg-muted">Еда восстанавливает сытость. Проигрыш в бою будет снижать голод.</p><button class="tg-btn" data-food ${st.coins<80?'disabled':''}>Поесть · 80 🪙</button></div>`)}
 function settings(){overlay('tgSettings','⚙️ Настройки',`<div class="tg-card"><b>Язык</b><p class="tg-muted">Русский / English. Основные игровые панели переключаются; текст, запечатанный непосредственно в арт-фоне, остаётся частью изображения.</p><button class="tg-btn" data-lang>${st.lang==='ru'?'Switch to English':'Переключить на русский'}</button></div><div class="tg-card"><b>Сохранение</b><p class="tg-muted">Прогресс хранится локально на устройстве.</p></div>`)}
 function messages(){overlay('tgMessages','✉️ Сообщения',`<div class="tg-card"><b>Система Territory</b><p class="tg-muted">Добро пожаловать в Sdolars. Город, PvE и Arena разделены.</p></div><div class="tg-card"><b>Alex</b><p class="tg-muted">«В Sdolars каждый воин может стать легендой.»</p></div>`)}
 function achievements(){overlay('tgAch','🏆 Достижения',`<div class="tg-grid"><div class="tg-stat"><b>🏰 Горожанин</b><small>Открой город</small></div><div class="tg-stat"><b>⚔️ Первый бой</b><small>Победи бота</small></div><div class="tg-stat"><b>🪙 Торговец</b><small>Купи предмет</small></div><div class="tg-stat"><b>👑 Охотник на боссов</b><small>Победи босса</small></div></div>`)}
 function equipment(){inventory()}
 const pve={enemy:null,attack:null,def:[],round:0,started:false};
 const enemies=[{name:'Разбойник у ворот',ico:'👹',hp:90,damage:10,reward:45,xp:12},{name:'Наёмник Sdolars',ico:'🗡️',hp:120,damage:14,reward:65,xp:17},{name:'Гвардеец замка',ico:'🛡️',hp:155,damage:18,reward:90,xp:23},{name:'Капитан стражи',ico:'⚔️',hp:195,damage:22,reward:125,xp:30}];
 function pveOpen(){pve.started=false;pve.attack=null;pve.def=[];pve.round=0;const o=overlay('tgPve','⚔️ Городской бой',`<div class="tg-card"><b>Городской путь · уровень ${st.cityLevel}</b><div class="tg-muted">Герой идёт вправо. Победы продвигают прогресс до 100%, затем появляется босс.</div><div class="tg-bar tg-progress"><i style="width:${st.pveProgress}%"></i></div><p>${st.pveProgress}% · ⚔️ Боевые камни: ${st.combatStone}</p></div><div id="tgPveBody"></div>`);renderPve(o.querySelector('#tgPveBody'));}
 function renderPve(host){if(!host)return; if(!pve.enemy){let idx=Math.min(enemies.length-1,Math.floor(st.pveProgress/30));pve.enemy={...enemies[idx],maxHp:enemies[idx].hp}}const e=pve.enemy;host.innerHTML=`<div class="tg-card"><div class="tg-enemy">${e.ico}</div><h3 style="text-align:center;margin:4px">${e.name}</h3><div class="tg-bar tg-hp"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></div><div class="tg-muted" style="text-align:center">${e.hp}/${e.maxHp} HP · Урон ${e.damage}</div></div><div class="tg-card"><b>1. Атака — выбери 1 зону</b><div class="tg-zones" style="margin-top:8px">${[['head','Голова'],['chest','Грудь'],['stomach','Живот'],['legs','Ноги']].map(x=>`<button class="tg-zone ${pve.attack===x[0]?'sel-a':''}" data-pve-a="${x[0]}">${x[1]}</button>`).join('')}</div><b style="display:block;margin-top:12px">2. Защита — выбери ровно 2 зоны</b><div class="tg-zones" style="margin-top:8px">${[['head','Голова'],['chest','Грудь'],['stomach','Живот'],['legs','Ноги']].map(x=>`<button class="tg-zone ${pve.def.includes(x[0])?'sel-d':''}" data-pve-d="${x[0]}">${x[1]}</button>`).join('')}</div><button class="tg-btn gold" style="width:100%;margin-top:12px" data-pve-hit ${!pve.attack||pve.def.length!==2||st.combatStone<1?'disabled':''}>⚔️ Нанести удар · 1 камень</button></div><div class="tg-card tg-log" id="tgPveLog"><b>Боевой журнал</b><div>Выбери атаку и две зоны защиты.</div></div>`}
 function pveAction(type,val,host){if(type==='a')pve.attack=val;else{const i=pve.def.indexOf(val);if(i>=0)pve.def.splice(i,1);else if(pve.def.length<2)pve.def.push(val)}renderPve(host)}
 function pveHit(host){if(st.combatStone<1||!pve.attack||pve.def.length!==2)return;st.combatStone--;pve.round++;let dmg=Math.max(4,5+st.strength+st.weaponMastery+st.bonusDamage);if(pve.attack==='head')dmg+=3;const crit=Math.random()<Math.min(.6,st.strength*.02);if(crit)dmg=Math.round(dmg*1.6);pve.enemy.hp=Math.max(0,pve.enemy.hp-dmg);let enemyHit=Math.max(0,pve.enemy.damage-(st.defense*1.5));if(pve.def.includes('head'))enemyHit=Math.max(0,enemyHit-3);if(pve.def.includes('chest'))enemyHit=Math.max(0,enemyHit-3);st.hp=Math.max(0,st.hp-enemyHit);let log=$('#tgPveLog');if(log){log.insertAdjacentHTML('beforeend',`<div>Раунд ${pve.round}: ты нанёс ${dmg}${crit?' КРИТ':''}. Противник ответил ${enemyHit}.</div>`);log.scrollTop=log.scrollHeight}if(pve.enemy.hp<=0){const boss=st.pveProgress>=100;if(boss){st.coins+=250;st.gems+=10;st.pveWins++;st.cityLevel++;st.pveProgress=0;toast('Босс побеждён! Новый уровень города.')}else{st.coins+=pve.enemy.reward;st.exp+=pve.enemy.xp;st.pveProgress=Math.min(100,st.pveProgress+20);toast('Победа! Путь продолжается.')}while(st.exp>=st.maxExp){st.exp-=st.maxExp;st.level++;st.freePoints+=3;st.maxExp=Math.round(st.maxExp*1.15);st.maxHp+=10;st.hp=st.maxHp}pve.enemy=null;pve.attack=null;pve.def=[];save();renderPve(host);return}if(st.hp<=0){st.hunger=Math.max(0,st.hunger-5);st.hp=Math.ceil(st.maxHp*.35);toast('Поражение. Голод -5%.')}const durId=st.equipped.weapon||null;if(durId){st.durability[durId]=Math.max(0,(st.durability[durId]??300)-1);if(st.durability[durId]===0)toast('Оружие сломалось — требуется ремонт.')}save();renderPve(host)}
 function arenaOpen(){let mode='duel',team=1,players=['SSS'];const o=overlay('tgArena','⚔️ Arena · PvP',`<div class="tg-card"><div class="tg-grid"><button class="tg-btn" data-amode="duel">1×1</button><button class="tg-btn" data-amode="chaos">Хаос</button><button class="tg-btn" data-amode="group">Группа до 20</button><button class="tg-btn" data-ateam="2">Команда 2</button></div><p class="tg-muted">Лобби: игрок создатель запускает бой через 3:00. В хаосе команды распределяются случайно.</p></div><div id="tgArenaBody"></div>`);const body=o.querySelector('#tgArenaBody');function draw(){body.innerHTML=`<div class="tg-card"><b>Лобби</b><div class="tg-muted">Игроков: ${players.length}/20 · режим: ${mode}</div><button class="tg-btn" data-addplayer>Добавить тестового игрока</button><button class="tg-btn gold" data-startarena style="width:100%;margin-top:8px">Начать сейчас</button></div>${mode==='duel'?'<div class="tg-card"><b>Ты против случайного бойца</b></div>':''}<div id="tgArenaFight"></div>`}function fight(){const f=body.querySelector('#tgArenaFight');f.innerHTML=`<div class="tg-card"><b>Раунд ${Math.floor(Math.random()*3)+1} · твоя команда ${team}</b><p class="tg-muted">Выбери цель, атаку и 2 защиты. Локальный прототип готов для последующего серверного WebSocket.</p><div class="tg-zones">${[['head','Голова'],['chest','Грудь'],['stomach','Живот'],['legs','Ноги']].map(x=>`<button class="tg-zone" data-aa="${x[0]}">${x[1]}</button>`).join('')}</div><div class="tg-card"><b>Боевой журнал</b><div>Команды распределены. Выберите действие.</div></div></div>`}draw();o.addEventListener('click',e=>{const m=e.target.closest('[data-amode]');if(m){mode=m.dataset.amode;draw()}const a=e.target.closest('[data-addplayer]');if(a&&players.length<20){players.push('Warrior '+players.length);draw()}const t=e.target.closest('[data-ateam]');if(t){team=2;toast('Ты выбрал команду 2')}if(e.target.closest('[data-startarena]'))fight()})}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-ui]');if(b){e.preventDefault();e.stopPropagation();({profile,bonuses,messages,achievements,settings,language:settings,events,vip,tavern})[b.dataset.ui]?.();return}const ds=e.target.closest('[data-screen]');if(ds&&ds.dataset.screen==='pve'){e.preventDefault();e.stopImmediatePropagation();pveOpen();return}if(ds&&ds.dataset.screen==='arena'){e.preventDefault();e.stopImmediatePropagation();arenaOpen();return}if(ds&&ds.dataset.screen==='inventory'){e.preventDefault();e.stopImmediatePropagation();inventory();return}if(ds&&ds.dataset.screen==='market'){e.preventDefault();e.stopImmediatePropagation();market();return}} ,true);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-addstat]');if(b&&st.freePoints>0){st[b.dataset.addstat]++;st.freePoints--;save();profile()}const buy=e.target.closest('[data-buyitem]');if(buy){const it=items.find(x=>x.id===buy.dataset.buyitem);if(it&&st.coins>=it.cost){st.coins-=it.cost;addItem(it);toast('Предмет куплен')}else toast('Не хватает монет')}const eq=e.target.closest('[data-equip]');if(eq){const it=items.find(x=>x.id===eq.dataset.equip);if(!it)return;if(st.equipped[it.id]){delete st.equipped[it.id];if(it.type==='weapon'){st.weapon='Кулаки';st.bonusDamage=0}}else{st.equipped[it.id]=true;if(it.type==='weapon'){st.weapon=it.name;st.bonusDamage=it.damage}}save();inventory()}if(e.target.closest('[data-daily]')){st.dailyClaim=new Date().toISOString().slice(0,10);st.coins+=100;st.combatStone+=5;save();bonuses()}if(e.target.closest('[data-vip]')){st.vipDays=1;save();vip()}if(e.target.closest('[data-food]')){if(st.coins>=80){st.coins-=80;st.hunger=Math.min(100,st.hunger+30);save();tavern()}}if(e.target.closest('[data-lang]')){st.lang=st.lang==='ru'?'en':'ru';save();settings()}if(e.target.closest('[data-eventclaim]'))toast('В городе новые встречи.')} );
 updateHud();
})();
