/* Territory G65 — Events, Daily & Rewards Hub.
   One city-facing hub for recurring rewards and temporary activities.
   Uses TerritoryEconomy for all currency changes. City artwork/PvE/Arena stay separate. */
(function(){'use strict';
 const $=s=>document.querySelector(s);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const st=window.TerritoryStore?.state||{};
 const eco=window.TerritoryEconomy;
 const KEY='territory_save_v1';
 const dayKey=()=>new Date().toISOString().slice(0,10);
 const ensure=()=>{st.g65=st.g65&&typeof st.g65==='object'?st.g65:{};st.g65.eventClaims=Array.isArray(st.g65.eventClaims)?st.g65.eventClaims:[];st.g65.rewardClaims=Array.isArray(st.g65.rewardClaims)?st.g65.rewardClaims:[];st.g65.vipUntil=Number(st.g65.vipUntil||0);st.g65.lastHub=String(st.g65.lastHub||'daily');};
 const save=(reason)=>{ensure();try{window.TerritoryStore.saveNow(reason||'g65')}catch(e){try{localStorage.setItem(KEY,JSON.stringify(st))}catch(_){} } window.dispatchEvent(new CustomEvent('territory:g65',{detail:{reason:reason||'g65'}})); if(typeof window.render==='function')window.render();};
 const reward=(pack,reason)=>{if(eco?.reward)return eco.reward(pack,reason);Object.entries(pack||{}).forEach(([k,v])=>{st[k]=Math.max(0,Number(st[k]||0)+Number(v||0))});save(reason);return pack};
 const toast=t=>{let x=$('#tgToast');if(!x){x=document.createElement('div');x.id='tgToast';x.className='tg-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)};
 function injectCss(){if($('#territory-g65-css'))return;const c=document.createElement('style');c.id='territory-g65-css';c.textContent=`
 #tgG65{position:fixed;inset:0;z-index:100006;display:none;align-items:flex-end;justify-content:center;background:rgba(1,6,10,.8);backdrop-filter:blur(6px)}
 #tgG65.show{display:flex}#tgG65 .g65-card{width:min(720px,100%);max-height:92vh;overflow:auto;background:linear-gradient(180deg,#15232c,#071116);color:#f3eadc;border:1px solid #765f3f;border-radius:22px 22px 0 0;box-shadow:0 -20px 60px #000c;padding:12px;box-sizing:border-box}
 .g65-head{display:flex;align-items:center;gap:9px;position:sticky;top:0;z-index:3;padding-bottom:9px;background:linear-gradient(#15232c 78%,transparent)}.g65-head h2{margin:0;flex:1;font:700 20px Georgia,serif;color:#f0d092}.g65-x{border:1px solid #80603d;background:#19262c;color:#f6dfae;border-radius:10px;padding:8px 11px;font-weight:900}
 .g65-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:3px 0 9px}.g65-tab{border:1px solid #30434d;border-radius:10px;background:#101b21;color:#aebbc2;padding:9px 4px;font-weight:900;font-size:10px}.g65-tab.active{border-color:#b1874c;background:#30271d;color:#f5d997}
 .g65-box{border:1px solid #30434d;border-radius:14px;background:#0d1a20;padding:11px;margin:8px 0}.g65-row{display:grid;grid-template-columns:36px 1fr auto;gap:9px;align-items:center}.g65-ico{font-size:25px;text-align:center}.g65-title{font-weight:900}.g65-muted{font-size:11px;color:#9eafb8;line-height:1.35;margin-top:3px}.g65-value{font-size:17px;font-weight:900;color:#f0cf80;text-align:right}.g65-bar{height:7px;background:#071015;border:1px solid #2b3d45;border-radius:8px;overflow:hidden;margin-top:7px}.g65-bar i{display:block;height:100%;background:#d1ad55}.g65-btn{width:100%;margin-top:9px;border:1px solid #8e6a3f;border-radius:11px;background:linear-gradient(#664728,#34251b);color:#f8dfad;padding:10px;font-weight:900}.g65-btn:disabled{opacity:.45}.g65-event{position:relative}.g65-badge{position:absolute;right:10px;top:10px;font-size:8px;padding:4px 6px;border-radius:7px;background:#293a31;color:#a9e0aa}.g65-badge.hot{background:#402c25;color:#f0ad8c}.g65-rewards{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.g65-reward{padding:9px 5px;border:1px solid #334750;border-radius:10px;background:#111f26;text-align:center;font-size:10px}.g65-reward b{display:block;font-size:14px;color:#f0d18b}.g65-small{font-size:9px;color:#7e909a}.g65-vip{border-color:#755b36;background:linear-gradient(135deg,#201d17,#10191d)}
 @media(max-width:380px){#tgG65 .g65-card{padding:9px}.g65-tab{font-size:9px;padding:8px 2px}.g65-title{font-size:12px}}
 `;document.head.appendChild(c)}
 function open(tab='daily'){ensure();injectCss();let o=$('#tgG65');if(!o){o=document.createElement('div');o.id='tgG65';o.innerHTML='<div class="g65-card"><div class="g65-head"><h2>🎁 События и награды</h2><button class="g65-x">✕</button></div><div class="g65-tabs"><button class="g65-tab" data-g65-tab="daily">🎁 День</button><button class="g65-tab" data-g65-tab="events">📅 События</button><button class="g65-tab" data-g65-tab="rewards">🏆 Награды</button><button class="g65-tab" data-g65-tab="vip">👑 VIP</button></div><div id="g65Body"></div></div>';document.body.appendChild(o);o.querySelector('.g65-x').onclick=()=>o.classList.remove('show');o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show')})}o.classList.add('show');render(tab)}
 function render(tab){ensure();st.g65.lastHub=tab;const body=$('#g65Body');if(!body)return;document.querySelectorAll('[data-g65-tab]').forEach(b=>b.classList.toggle('active',b.dataset.g65Tab===tab));const today=dayKey();
  if(tab==='daily'){const claimed=st.dailyClaim===today;const streak=Number(st.daily?.streak||0);const next=100+Math.min(100,(streak+1)*10);body.innerHTML=`<div class="g65-box"><div class="g65-row"><div class="g65-ico">🌅</div><div><div class="g65-title">Ежедневный бонус</div><div class="g65-muted">Заходи каждый день и получай монеты и боевые камни. Серия: ${streak} дн.</div><div class="g65-bar"><i style="width:${Math.min(100,streak/7*100)}%"></i></div></div><div class="g65-value">+${next} 🪙</div></div><button class="g65-btn" data-g65-daily ${claimed?'disabled':''}>${claimed?'✓ Сегодня получено':'Забрать сегодня'}</button></div><div class="g65-box"><div class="g65-title">Текущие ресурсы</div><div class="g65-rewards"><div class="g65-reward"><b>${st.coins||0}</b>🪙<div class="g65-small">монеты</div></div><div class="g65-reward"><b>${st.gems||0}</b>💎<div class="g65-small">алмазы</div></div><div class="g65-reward"><b>${st.combatStone||0}</b>💜<div class="g65-small">боевые камни</div></div></div></div>`;return}
  if(tab==='events'){const events=[{id:'city',ico:'🏰',title:'События Sdolars',desc:'Городские встречи, караваны и поручения. Проверяй их после новых действий.',reward:{coins:80,combatStone:2},text:'+80 🪙 +2 💜'},{id:'caravan',ico:'🐎',title:'Караван у ворот',desc:'Временная городская активность. Доступна один раз за текущий день.',reward:{coins:120},text:'+120 🪙'},{id:'forge',ico:'🔨',title:'День кузнеца',desc:'Поддерживай экипировку в порядке и получай небольшую награду.',reward:{coins:60},text:'+60 🪙'}];body.innerHTML=events.map(ev=>{const claim=st.g65.eventClaims.includes(ev.id+'@'+today);return `<div class="g65-box g65-event"><span class="g65-badge ${claim?'':'hot'}">${claim?'ПОЛУЧЕНО':'СЕГОДНЯ'}</span><div class="g65-row"><div class="g65-ico">${ev.ico}</div><div><div class="g65-title">${ev.title}</div><div class="g65-muted">${ev.desc}</div></div><div class="g65-value">${ev.text}</div></div><button class="g65-btn" data-g65-event="${ev.id}" ${claim?'disabled':''}>${claim?'✓ Забрано':'Забрать награду'}</button></div>`}).join('');return}
  if(tab==='rewards'){const milestones=[{id:'lvl2',ico:'⭐',title:'Уровень 2',desc:'Достигни 2 уровня персонажа.',ok:Number(st.level)>=2,reward:{coins:200,gems:5},text:'+200 🪙 +5 💎'},{id:'pve5',ico:'⚔️',title:'Городской боец',desc:'Победи 5 противников в PvE.',ok:Number(st.pveWins)>=5,reward:{coins:250,combatStone:5},text:'+250 🪙 +5 💜'},{id:'rep5',ico:'🧔',title:'Доверие Alex',desc:'Набери 5 репутации Sdolars.',ok:Number(st.cityRep)>=5,reward:{coins:180,gems:3},text:'+180 🪙 +3 💎'}];body.innerHTML=milestones.map(m=>{const claimed=st.g65.rewardClaims.includes(m.id);const ready=m.ok&&!claimed;return `<div class="g65-box"><div class="g65-row"><div class="g65-ico">${m.ico}</div><div><div class="g65-title">${m.title}</div><div class="g65-muted">${m.desc}</div></div><div class="g65-value">${m.text}</div></div><button class="g65-btn" data-g65-reward="${m.id}" ${!ready?'disabled':''}>${claimed?'✓ Получено':m.ok?'Забрать':'Ещё не выполнено'}</button></div>`}).join('');return}
  const active=Number(st.g65.vipUntil||0)>Date.now();body.innerHTML=`<div class="g65-box g65-vip"><div class="g65-row"><div class="g65-ico">👑</div><div><div class="g65-title">VIP Sdolars</div><div class="g65-muted">Прототипная VIP-система без реальных платежей. Активный VIP отмечает доступность дополнительных бонусов.</div></div><div class="g65-value">${active?'АКТИВЕН':'—'}</div></div><div class="g65-muted">${active?'До '+new Date(st.g65.vipUntil).toLocaleString():'Тестовый VIP можно активировать на 24 часа.'}</div><button class="g65-btn" data-g65-vip ${active?'disabled':''}>${active?'✓ VIP активен':'Активировать VIP на 24 часа'}</button></div><div class="g65-box"><div class="g65-title">Без реальных денег</div><div class="g65-muted">На прототипном этапе покупки за реальные деньги не подключаются. Экономика работает только внутриигровыми ресурсами.</div></div>`;
 }
 document.addEventListener('click',e=>{const tab=e.target.closest('[data-g65-tab]');if(tab){e.preventDefault();e.stopImmediatePropagation();open(tab.dataset.g65Tab);return}if(e.target.closest('[data-g65-daily]')){e.preventDefault();e.stopImmediatePropagation();ensure();const r=eco?.claimDaily?.();if(r?.ok){toast(`🎁 +${r.coins} 🪙 +${r.combatStone} 💜`);save('daily-claim')}else toast('Бонус за сегодня уже получен');render('daily');return}const ev=e.target.closest('[data-g65-event]');if(ev){e.preventDefault();e.stopImmediatePropagation();ensure();const id=ev.dataset.g65Event+'@'+dayKey();if(st.g65.eventClaims.includes(id)){toast('Уже получено');return}const packs={city:{coins:80,combatStone:2},caravan:{coins:120},forge:{coins:60}};reward(packs[ev.dataset.g65Event],'event:'+ev.dataset.g65Event);st.g65.eventClaims.push(id);save('event-claim');toast('📦 Награда получена');render('events');return}const rw=e.target.closest('[data-g65-reward]');if(rw){e.preventDefault();e.stopImmediatePropagation();ensure();const id=rw.dataset.g65Reward;if(st.g65.rewardClaims.includes(id)){toast('Уже получено');return}const packs={lvl2:{coins:200,gems:5},pve5:{coins:250,combatStone:5},rep5:{coins:180,gems:3}};const ok={lvl2:Number(st.level)>=2,pve5:Number(st.pveWins)>=5,rep5:Number(st.cityRep)>=5}[id];if(!ok){toast('Условие ещё не выполнено');return}reward(packs[id],'milestone:'+id);st.g65.rewardClaims.push(id);save('milestone-claim');toast('🏆 Награда получена');render('rewards');return}if(e.target.closest('[data-g65-vip]')){e.preventDefault();e.stopImmediatePropagation();ensure();st.g65.vipUntil=Date.now()+86400000;st.vipDays=1;save('vip-activate');toast('👑 VIP активирован на 24 часа');render('vip');return}},true);
 document.addEventListener('click',e=>{const q=e.target.closest('[data-ui="bonuses"],[data-g59="bonuses"]');if(q){e.preventDefault();e.stopImmediatePropagation();open('daily');return}const q2=e.target.closest('[data-ui="events"],[data-g59="events"]');if(q2){e.preventDefault();e.stopImmediatePropagation();open('events');return}const q3=e.target.closest('[data-ui="vip"],[data-g59="vip"]');if(q3){e.preventDefault();e.stopImmediatePropagation();open('vip');return}},true);
 ensure();window.TerritoryEvents={version:'G65',open,refresh:()=>render(st.g65.lastHub||'daily')};
})();
