/* Territory G68 — Character / Inventory / Equipment Hub
   One player-facing equipment UI over the existing TerritoryCharacter core.
   City art, PvE and Arena remain untouched. */
(function(){'use strict';
 const Store=window.TerritoryStore, Char=window.TerritoryCharacter;
 if(!Store||!Char)return;
 const st=Store.state, items=Char.items;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const slots=[['weapon','⚔️','Оружие'],['helmet','🪖','Шлем'],['armor','🛡️','Броня'],['gloves','🥊','Перчатки'],['boots','🥾','Сапоги']];
 const save=()=>{Char.save();if(typeof window.render==='function')window.render();window.dispatchEvent(new CustomEvent('territory:character-updated'));};
 const toast=t=>{let x=document.getElementById('tgToast');if(!x){x=document.createElement('div');x.id='tgToast';x.className='tg-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1700)};
 function css(){if(document.getElementById('tgG68css'))return;const c=document.createElement('style');c.id='tgG68css';c.textContent=`
 #tgG68{position:fixed;inset:0;z-index:100030;display:none;align-items:flex-end;justify-content:center;background:rgba(2,5,8,.84);padding:9px;box-sizing:border-box;touch-action:manipulation}
 #tgG68.show{display:flex}.g68-card{width:min(720px,100%);max-height:94vh;overflow:auto;border:1px solid #735c3d;border-radius:22px 22px 0 0;background:linear-gradient(180deg,#17242c,#091015);color:#f3eadc;padding:13px;box-sizing:border-box;box-shadow:0 -20px 70px #000c}.g68-head{display:flex;align-items:center;gap:8px;position:sticky;top:0;z-index:5;padding-bottom:9px;background:linear-gradient(#17242c 78%,transparent)}.g68-head h2{margin:0;flex:1;font:700 21px Georgia,serif;color:#efd08e}.g68-x{width:40px;height:40px;border:1px solid #6d5638;border-radius:11px;background:#172027;color:#f2d69c;font-weight:900}.g68-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:9px}.g68-tab,.g68-btn{border:1px solid #334750;border-radius:10px;background:#101b21;color:#dce4e5;padding:9px;font-weight:900}.g68-tab.active{border-color:#a47d43;background:#30271d;color:#f5d995}.g68-btn.gold{border-color:#8f6b3d;background:linear-gradient(#67482a,#36251a);color:#f6dda7}.g68-box{border:1px solid #2d4149;border-radius:14px;background:#0d1a20;padding:11px;margin:8px 0}.g68-statgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.g68-stat{padding:9px;border:1px solid #293b43;border-radius:10px;background:#111e24}.g68-stat small{display:block;color:#899aa2;font-size:10px}.g68-stat b{display:block;color:#efd18c;font-size:16px;margin-top:2px}.g68-slots{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.g68-slot{padding:9px;border:1px solid #293b43;border-radius:11px;background:#111e24;display:flex;gap:8px;align-items:center}.g68-slot.weapon{grid-column:1/-1}.g68-slot i{font-style:normal;font-size:24px}.g68-slot small{display:block;color:#8ea0a8;font-size:9px}.g68-slot b{font-size:12px}.g68-item{display:grid;grid-template-columns:40px 1fr auto;gap:8px;align-items:center}.g68-icon{font-size:27px;text-align:center}.g68-grow{min-width:0}.g68-grow b{font-size:13px}.g68-muted{color:#95a5ad;font-size:10px;line-height:1.35;margin-top:3px}.g68-dur{font-size:10px;color:#d2b56e;margin-top:4px}.g68-actions{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.g68-actions button{padding:8px 9px}.g68-danger{border-color:#654143!important;color:#e5aaaa!important}.g68-empty{padding:16px;text-align:center;color:#819198;border:1px dashed #30434b;border-radius:12px}.g68-note{font-size:10px;color:#7e9098;line-height:1.4}.g68-total{display:grid;grid-template-columns:1fr 1fr;gap:7px}.g68-total div{padding:9px;border-radius:10px;background:#111e24;text-align:center}.g68-total b{display:block;color:#efd18c;font-size:17px}.g68-total small{color:#899aa2;font-size:9px}@media(max-width:380px){.g68-card{padding:9px}.g68-item{grid-template-columns:34px 1fr}.g68-actions{grid-column:2}.g68-actions button{flex:1}.g68-slot b{font-size:11px}}
 `;document.head.appendChild(c)}
 function open(tab='equipment'){css();let o=document.getElementById('tgG68');if(!o){o=document.createElement('div');o.id='tgG68';o.innerHTML='<div class="g68-card"><div class="g68-head"><h2>🎒 Герой и снаряжение</h2><button class="g68-x" data-g68="close">✕</button></div><div class="g68-tabs"><button class="g68-tab" data-g68-tab="equipment">⚔️ Экипировка</button><button class="g68-tab" data-g68-tab="inventory">🎒 Инвентарь</button><button class="g68-tab" data-g68-tab="stats">📊 Характеристики</button></div><div id="g68Body"></div></div>';document.body.appendChild(o)}o.classList.add('show');render(tab)}
 function itemCount(id){return st.inventory.filter(x=>x===id).length}
 function equipment(){const eq=Char.derived();const slotHtml=slots.map(([slot,ico,label])=>{const id=st.equipmentSlots?.[slot];const it=id&&Char.find(id);const d=it?Math.max(0,Number(st.durability[id]??it.maxDurability)):0;return `<div class="g68-slot ${slot}"><i>${ico}</i><div><small>${label}</small><b>${it?esc(it.name):'Пусто'}</b>${it?`<small>Прочность ${d}/${it.maxDurability}</small>`:''}</div></div>`}).join('');document.getElementById('g68Body').innerHTML=`<div class="g68-box"><div class="g68-slots">${slotHtml}</div><div class="g68-total" style="margin-top:8px"><div><b>+${eq.equipment.damage}</b><small>урон от экипировки</small></div><div><b>+${eq.equipment.defense}</b><small>защита от экипировки</small></div></div></div><div class="g68-box"><b>Активное снаряжение</b><div class="g68-muted">Ниже показаны только вещи, которыми можно управлять прямо сейчас.</div></div>${inventoryList(true)}`}
 function inventoryList(equippedFirst=false){const ids=[...new Set(st.inventory)];if(!ids.length)return '<div class="g68-empty">Инвентарь пуст.</div>';const ordered=equippedFirst?ids.sort((a,b)=>{const ea=st.equipmentSlots[Char.slotFor(a)]===a?1:0,eb=st.equipmentSlots[Char.slotFor(b)]===b?1:0;return eb-ea}):ids;return ordered.map(id=>{const it=Char.find(id)||{id,name:id,icon:'📦',slot:'armor',maxDurability:300};const count=itemCount(id), active=st.equipmentSlots?.[it.slot]===id, d=Math.max(0,Number(st.durability[id]??it.maxDurability));return `<div class="g68-box g68-item"><div class="g68-icon">${it.icon}</div><div class="g68-grow"><b>${esc(it.name)}${count>1?' ×'+count:''}</b><div class="g68-muted">${it.damage?'Урон +'+it.damage+' · ':''}${it.defense?'Защита +'+it.defense+' · ':''}слот: ${esc(it.slot)}</div><div class="g68-dur">${active?'НАДЕТО · ':''}Прочность ${d}/${it.maxDurability}</div></div><div class="g68-actions"><button class="g68-btn gold" data-g68-equip="${it.id}">${active?'Снять':'Надеть'}</button><button class="g68-btn g68-danger" data-g68-discard="${it.id}">Выбросить</button></div></div>`}).join('')}
 function inventory(){document.getElementById('g68Body').innerHTML=`<div class="g68-box"><b>Предметы героя</b><div class="g68-muted">Один предмет занимает свой слот. Дубликаты хранятся количеством.</div></div>${inventoryList(false)}<div class="g68-box"><button class="g68-btn gold" style="width:100%" data-g68="repair">🔨 Открыть кузницу</button></div>`}
 function stats(){const d=Char.derived();document.getElementById('g68Body').innerHTML=`<div class="g68-box"><b>${esc(st.name)} · уровень ${st.level}</b><div class="g68-muted">Опыт ${st.exp}/${st.maxExp} · свободные очки ${st.freePoints}</div></div><div class="g68-statgrid">${[['Сила',st.strength],['Ловкость',st.agility],['Защита',st.defense],['Выносливость',st.endurance],['Мастерство оружия',st.weaponMastery],['Макс. HP',d.maxHp],['Крит',d.crit+'%'],['Уворот',d.dodge+'%'],['Урон',d.damage],['Блок',d.block+'%'],['Сила героя',d.power],['Голод',st.hunger+'%']].map(x=>`<div class="g68-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><div class="g68-box"><div class="g68-note">Характеристики считаются из единого Character Core. Бонусы исправной экипировки учитываются автоматически; сломанные предметы не дают бонусов.</div></div>`}
 function render(tab){document.querySelectorAll('[data-g68-tab]').forEach(b=>b.classList.toggle('active',b.dataset.g68Tab===tab));if(tab==='inventory')inventory();else if(tab==='stats')stats();else equipment()}
 function repair(){if(window.TerritoryCore?.openRepair){document.getElementById('tgG68')?.classList.remove('show');window.TerritoryCore.openRepair();return}open('inventory')}
 function equip(id){const it=Char.find(id);if(!it)return;const ok=Char.equip(id);if(ok){save();toast(st.equipmentSlots[it.slot]===id?'⚔️ Предмет надет':'Предмет снят')}render('inventory')}
 function discard(id){const it=Char.find(id);if(!it)return;const active=st.equipmentSlots?.[it.slot]===id;if(active)Char.equip(id);const idx=st.inventory.indexOf(id);if(idx<0)return;st.inventory.splice(idx,1);delete st.durability[id];save();toast('🗑️ Предмет выброшен');render('inventory')}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-g68]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const a=b.dataset.g68;if(a==='close')document.getElementById('tgG68')?.classList.remove('show');else if(a==='repair')repair()},true);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-g68-tab]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open(b.dataset.g68Tab)},true);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-g68-equip]');if(b){e.preventDefault();e.stopImmediatePropagation();equip(b.dataset.g68Equip);return}const d=e.target.closest('[data-g68-discard]');if(d){e.preventDefault();e.stopImmediatePropagation();discard(d.dataset.g68Discard);return}},true);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-screen="inventory"],[data-g59="inventory"],[data-g59="equipment"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open('equipment')},true);
 window.TerritoryCharacterHub={version:'G68',open,refresh:()=>render('equipment')};
})();
